-- =====================================================================
-- V10 — ENT-018 Currency (settings module).
--
-- Global reference data shared across all companies (intentionally not
-- tenant-scoped). Matches com.springboot.erp.modules.settings.currency.domain.Currency
-- extending BaseEntity. Exactly one row may be default, enforced by a partial
-- unique index (Postgres has no declarative partial-unique constraint).
-- =====================================================================

create table currencies (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    code            char(3)      not null,          -- ISO 4217, immutable
    name            varchar(100) not null,
    short_name      varchar(20)  not null,
    country         varchar(100) not null,
    symbol          varchar(8)   not null,
    decimal_places  integer      not null default 2,

    is_default      boolean      not null default false,
    is_active       boolean      not null default true,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint uq_currencies_code unique (code),
    constraint ck_currencies_decimal_places_range
        check (decimal_places >= 0 and decimal_places <= 4)
);

-- Partial unique: at most one default currency at a time.
create unique index uq_currencies_default
    on currencies (is_default)
    where is_default = true;

-- Permissions for the currency slice (mirrors the settings.<concept>.read/write
-- convention seeded in V2 / V13). Granted to the admin role so the endpoints are
-- reachable — without these rows the @PreAuthorize checks would always 403.
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM09', 'settings.currency.read',  'View currencies',   'settings', 'List and view currencies'),
  ('01J0AA000000000000PERM10', 'settings.currency.write', 'Manage currencies', 'settings', 'Create, update, delete, and set the default currency');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in ('settings.currency.read', 'settings.currency.write')
where r.code = 'admin';
