-- =====================================================================
-- V11 — ENT-007 Tax Code (settings.taxcode module, US-003 / FR-012-016).
--
-- Ported from the reference app.tax_codes SQLAlchemy model. Tax codes are
-- scoped to a company via `company_public_id` (the company's ULID); the v2
-- companies module is not yet ported, so the parent is referenced by its
-- public id rather than an internal FK. Multiple effective ranges per code are
-- allowed (FR-014); overlapping ranges for the same (company, code) are
-- rejected in the service layer (the reference's Postgres GIST exclude mirror).
-- =====================================================================

create table tax_codes (
    id                 bigint generated by default as identity primary key,
    public_id          char(26)      not null unique,
    company_public_id  char(26)      not null,
    code               varchar(20)   not null,
    description        varchar(200)  not null,
    rate_percent       numeric(5, 2) not null,
    is_inclusive       boolean       not null default false,
    is_exempt          boolean       not null default false,
    gst_treatment      varchar(20)   not null default 'STANDARD',
    effective_from     date          not null,
    effective_to       date,
    created_at         timestamptz   not null default now(),
    created_by         char(26),
    updated_at         timestamptz   not null default now(),
    updated_by         char(26),
    deleted_at         timestamptz,
    version            bigint        not null default 0,
    constraint uq_tax_codes_company_code_effective_from
        unique (company_public_id, code, effective_from),
    constraint ck_tax_codes_rate_range
        check (rate_percent >= 0 and rate_percent <= 100),
    constraint ck_tax_codes_effective_range
        check (effective_to is null or effective_to >= effective_from),
    constraint ck_tax_codes_gst_treatment
        check (gst_treatment in ('STANDARD', 'GST_FREE', 'EXPORT', 'INPUT_TAXED'))
);

-- Company scoping filter (reference indexed company_id).
create index idx_tax_codes_company on tax_codes (company_public_id);
