-- =====================================================================
-- V12 — ENT-002 Location (settings.location vertical slice).
--
-- Mirrors com.springboot.erp.modules.settings.location.domain.Location. Domain
-- columns + the BaseEntity columns (public_id, audit, soft delete,
-- optimistic lock). Belongs to one company via a bigint `company_id`
-- (reference: locations.company_id → companies.id on delete restrict).
-- Code uniqueness is scoped to that company.
--
-- NOTE ON THE COMPANY FK: the companies table is created by the company
-- slice's migration (V14), which Flyway applies AFTER this V12. Declaring a
-- database FK here would fail because the target table does not exist yet, and
-- reordering the migrations is out of scope for this task. Referential
-- integrity is therefore enforced at the application layer by the JPA
-- @ManyToOne (LocationService loads/validates the company and 404s if missing).
-- Add the DB-level FK in a later migration once both slices ship together:
--   alter table locations add constraint fk_locations_company
--     foreign key (company_id) references companies (id) on delete restrict;
-- =====================================================================

create table locations (
    id                          bigint generated by default as identity primary key,
    public_id                   char(26)      not null unique,
    company_id                  bigint        not null,
    code                        varchar(10)   not null,
    name                        varchar(200)  not null,
    type                        varchar(32)   not null,
    timezone                    varchar(50)   not null,
    address                     jsonb         not null,
    phone                       varchar(30),
    public_email                varchar(200),
    default_price_list_id       char(26),
    default_tax_code_id         char(26),
    status                      varchar(16)   not null default 'active',
    price_display_mode          varchar(16),
    created_at                  timestamptz   not null default now(),
    created_by                  char(26),
    updated_at                  timestamptz   not null default now(),
    updated_by                  char(26),
    deleted_at                  timestamptz,
    version                     bigint        not null default 0,

    constraint uq_locations_company_code unique (company_id, code),
    constraint ck_locations_type check (
        type in ('STORE', 'WAREHOUSE', 'OFFICE', 'HEAD_OFFICE',
                 'DISTRIBUTION_CENTER', 'FACTORY', 'OUTLET', 'SHOWROOM')),
    constraint ck_locations_status check (status in ('active', 'inactive')),
    constraint ck_locations_price_display_mode check (
        price_display_mode is null or price_display_mode in ('INCLUSIVE', 'EXCLUSIVE'))
);

-- Scope-to-company list filter (?company_id=…) hits this often.
create index idx_locations_company on locations (company_id);
