-- =====================================================================
-- V13 — ENT-006 Numbering Rule (US-005 / FR-022-025).
--
-- One rule per (company, document type) issues running sequence numbers.
-- Columns match com.guru.erp.modules.settings.numbering.domain.NumberingRule
-- plus the BaseEntity columns (public_id, audit, soft delete, optimistic lock).
--
-- company_id holds the owning company's public id (ULID) — v2 has no companies
-- table yet, so it is a plain char(26), not a FK. Revisit when companies land.
-- =====================================================================

create table numbering_rules (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)    not null unique,
    company_id          char(26)    not null,
    document_type       varchar(20) not null,
    prefix              varchar(10) not null default '',
    padding             integer     not null,
    reset_cadence       varchar(10) not null default 'NEVER',
    start_value         bigint      not null default 1,
    current_value       bigint      not null default 0,
    current_window_key  varchar(10) not null default '',
    total_issued        bigint      not null default 0,
    created_at          timestamptz not null default now(),
    created_by          char(26),
    updated_at          timestamptz not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint      not null default 0,
    constraint uq_numbering_rules_company_doctype unique (company_id, document_type),
    constraint ck_numbering_rules_document_type check (
        document_type in ('INVOICE','PO','PR','GRN','BILL','RECEIPT','DELIVERY','QUOTE','SO','JOURNAL')),
    constraint ck_numbering_rules_reset_cadence check (
        reset_cadence in ('NEVER','YEARLY','MONTHLY')),
    constraint ck_numbering_rules_padding check (padding between 4 and 10),
    constraint ck_numbering_rules_start_value check (start_value >= 1)
);

create index idx_numbering_rules_company on numbering_rules (company_id);

-- Permissions for the numbering slice (mirrors the settings.<concept>.read/write
-- convention seeded in V2). Granted to the admin role.
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM07', 'settings.numbering.read',  'View numbering rules',   'settings', 'List and view numbering rules'),
  ('01J0AA000000000000PERM08', 'settings.numbering.write', 'Manage numbering rules', 'settings', 'Create, update, and allocate numbering rules');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in ('settings.numbering.read', 'settings.numbering.write')
where r.code = 'admin';
