-- =====================================================================
-- V14 — ENT-001 Company (settings.company vertical slice).
--
-- Matches com.guru.erp.modules.settings.company.domain.Company + BaseEntity.
-- Constraints reproduced from the reference SQLAlchemy model:
--   * unique(code)                       — FR-001
--   * partial unique on is_primary=true  — FR-004 (exactly one primary)
--   * partial unique on abn is not null  — FR-AU-001 (ABN uniqueness)
--   * check status / compliance_profile / bas_period enum values
-- Soft-deleted rows keep their partial-unique slot free via the deleted_at
-- guard in the partial indexes.
-- =====================================================================

create table companies (
    id                    bigint generated by default as identity primary key,
    public_id             char(26)     not null unique,

    code                  varchar(10)  not null,
    legal_name            varchar(200) not null,
    trading_name          varchar(200),
    country               varchar(2)   not null,
    base_currency         varchar(3)   not null,
    tax_registration_no   varchar(30),
    tax_registered        boolean      not null default false,
    tax_registration_date date,
    fiscal_year_start     varchar(5)   not null,
    is_primary            boolean      not null default false,
    status                varchar(16)  not null default 'active',
    compliance_profile    varchar(16)  not null default 'NONE',
    abn                   varchar(11),
    acn                   varchar(9),
    gst_registration_date date,
    bas_period            varchar(16),
    logo_url              text,
    invoice_layout        jsonb,

    created_at            timestamptz  not null default now(),
    created_by            char(26),
    updated_at            timestamptz  not null default now(),
    updated_by            char(26),
    deleted_at            timestamptz,
    version               bigint       not null default 0,

    constraint uq_companies_code unique (code),
    constraint ck_companies_status
        check (status in ('active', 'inactive')),
    constraint ck_companies_compliance_profile
        check (compliance_profile in ('NONE', 'AU')),
    constraint ck_companies_bas_period
        check (bas_period is null or bas_period in ('MONTHLY', 'QUARTERLY', 'ANNUAL'))
);

-- FR-004: at most one primary company among live rows.
create unique index uq_companies_primary
    on companies (is_primary)
    where is_primary = true and deleted_at is null;

-- FR-AU-001: ABN unique among live rows that supply one.
create unique index uq_companies_abn
    on companies (abn)
    where abn is not null and deleted_at is null;
