-- =====================================================================
-- V1 — Foundation schema (platform + access) for Guru ERP v2.
--
-- NOTE: ARCHITECTURE.md §2 calls for the full ~100-table baseline to come
-- from `pg_dump --schema-only` of the reference guru_erp DB. That requires the
-- reference database to be running and is tracked separately. This migration
-- establishes the cross-cutting platform tables + the access (RBAC) tables the
-- pilot module needs, all matching the JPA entities in com.guru.erp.platform.
-- Forward changes go in V2+.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Audit: append-only, hash-chained. UPDATE/DELETE are REVOKEd below so the
-- chain is tamper-evident (ARCHITECTURE.md §2).
-- ---------------------------------------------------------------------
create table audit_logs (
    id                bigint generated by default as identity primary key,
    entity_type       varchar(100) not null,
    entity_public_id  char(26),
    action            varchar(16)  not null,
    actor_public_id   char(26),
    request_id        char(26),
    before_data       jsonb,
    after_data        jsonb,
    prev_hash         char(64),
    row_hash          char(64)     not null,
    created_at        timestamptz  not null default now()
);
create index idx_audit_entity on audit_logs (entity_type, entity_public_id);
create index idx_audit_created on audit_logs (created_at);

-- ---------------------------------------------------------------------
-- Outbox: transactional event bus (POS -> GL -> Inv -> CRM).
-- ---------------------------------------------------------------------
create table outbox_events (
    id                   bigint generated by default as identity primary key,
    public_id            char(26)     not null unique,
    aggregate_type       varchar(100) not null,
    aggregate_public_id  char(26),
    event_type           varchar(100) not null,
    payload              jsonb        not null,
    created_at           timestamptz  not null default now(),
    processed_at         timestamptz,
    attempts             integer      not null default 0
);
create index idx_outbox_unprocessed on outbox_events (id) where processed_at is null;

-- ---------------------------------------------------------------------
-- Status master + history: reusable lookup + per-entity status trail.
-- ---------------------------------------------------------------------
create table status_master (
    id           bigint generated by default as identity primary key,
    public_id    char(26)     not null unique,
    domain       varchar(64)  not null,   -- e.g. 'invoice', 'purchase_order'
    code         varchar(64)  not null,   -- e.g. 'draft', 'cleared'
    label        varchar(128) not null,
    sort_order   integer      not null default 0,
    is_terminal  boolean      not null default false,
    created_at   timestamptz  not null default now(),
    unique (domain, code)
);

create table status_history (
    id                bigint generated by default as identity primary key,
    entity_type       varchar(100) not null,
    entity_public_id  char(26)     not null,
    from_code         varchar(64),
    to_code           varchar(64)  not null,
    actor_public_id   char(26),
    note              varchar(500),
    created_at        timestamptz  not null default now()
);
create index idx_status_history_entity on status_history (entity_type, entity_public_id);

-- ---------------------------------------------------------------------
-- Access (RBAC): users, roles, permissions + join tables.
-- Columns mirror com.guru.erp.platform.entity.BaseEntity (public_id, audit,
-- soft delete, optimistic lock).
-- ---------------------------------------------------------------------
create table permissions (
    id           bigint generated by default as identity primary key,
    public_id    char(26)     not null unique,
    code         varchar(120) not null unique,   -- e.g. 'access.user.read'
    name         varchar(160) not null,
    module       varchar(64)  not null,
    description  varchar(500),
    created_at   timestamptz  not null default now(),
    created_by   char(26),
    updated_at   timestamptz  not null default now(),
    updated_by   char(26),
    deleted_at   timestamptz,
    version      bigint       not null default 0
);

create table roles (
    id           bigint generated by default as identity primary key,
    public_id    char(26)     not null unique,
    code         varchar(120) not null unique,   -- e.g. 'admin'
    name         varchar(160) not null,
    description  varchar(500),
    is_system    boolean      not null default false,
    created_at   timestamptz  not null default now(),
    created_by   char(26),
    updated_at   timestamptz  not null default now(),
    updated_by   char(26),
    deleted_at   timestamptz,
    version      bigint       not null default 0
);

create table users (
    id             bigint generated by default as identity primary key,
    public_id      char(26)     not null unique,
    username       varchar(120) not null unique,
    email          varchar(255) not null unique,
    full_name      varchar(200) not null,
    password_hash  varchar(100) not null,
    is_active      boolean      not null default true,
    created_at     timestamptz  not null default now(),
    created_by     char(26),
    updated_at     timestamptz  not null default now(),
    updated_by     char(26),
    deleted_at     timestamptz,
    version        bigint       not null default 0
);

create table role_permissions (
    role_id        bigint not null references roles (id) on delete cascade,
    permission_id  bigint not null references permissions (id) on delete cascade,
    primary key (role_id, permission_id)
);

create table user_roles (
    user_id  bigint not null references users (id) on delete cascade,
    role_id  bigint not null references roles (id) on delete cascade,
    primary key (user_id, role_id)
);

-- ---------------------------------------------------------------------
-- Tamper-evidence: audit is append-only. Revoke mutation from the app role.
-- (The migration runs as the owner; the app connects as the same role here,
-- so we enforce at the app-role level. Adjust when a dedicated role exists.)
-- ---------------------------------------------------------------------
revoke update, delete on audit_logs from public;
