-- =====================================================================
-- V20 — PRODUCT module, "catalog" sub-slice.
--
-- Core product master aggregate + variants, barcodes, images, and custom
-- attribute values. Matches the JPA entities under
-- com.springboot.erp.modules.product.catalog.domain extending BaseEntity.
--
-- Cross-slice references (category, uom, supplier, tax code) are held as loose
-- ULID char(26) columns — no hard cross-slice FK (app-layer resolution per the
-- vertical-slice rule). Same-slice references (variant→product, barcode→product/
-- variant, image→product, custom-attr→product/variant) are real FKs.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-011 Product
-- ---------------------------------------------------------------------
create table products (
    id                              bigint generated by default as identity primary key,
    public_id                       char(26)     not null unique,

    sku                             varchar(50)  not null,
    name                            varchar(200) not null,
    description                     text,
    category_id                     char(26)     not null,           -- loose cross-slice ref
    brand                           varchar(100),
    supplier_id                     char(26),                        -- loose cross-slice ref (E-004)
    uom_id                          char(26)     not null,           -- loose cross-slice ref
    tax_code_id                     char(26),                        -- loose cross-slice ref

    cost_amount                     bigint       not null default 0,
    cost_currency                   char(3)      not null,
    po_cost_amount                  bigint       not null default 0,
    landed_cost_amount              bigint       not null default 0,
    sell_amount                     bigint       not null default 0,
    sell_currency                   char(3)      not null,

    weight_grams                    integer,
    dimensions                      jsonb,

    -- CR-001 (FR-283) weighed goods / label-printing scale integration.
    sold_by_weight                  boolean      not null default false,
    plu                             varchar(20),
    price_per_kg_amount             bigint,
    price_per_kg_synced_at          timestamptz,

    has_variants                    boolean      not null default false,
    is_active                       boolean      not null default true,
    lifecycle_state                 varchar(16)  not null default 'DRAFT',

    restriction_age_18              boolean      not null default false,
    restriction_age_21              boolean      not null default false,
    restriction_controlled_display  boolean      not null default false,
    restriction_note                varchar(500),

    created_at                      timestamptz  not null default now(),
    created_by                      char(26),
    updated_at                      timestamptz  not null default now(),
    updated_by                      char(26),
    deleted_at                      timestamptz,
    version                         bigint       not null default 0,

    constraint ck_products_lifecycle_state
        check (lifecycle_state in ('DRAFT','ACTIVE','ON_HOLD','RUN_OUT','DISCONTINUED')),
    constraint ck_products_cost_non_negative        check (cost_amount >= 0),
    constraint ck_products_po_cost_non_negative     check (po_cost_amount >= 0),
    constraint ck_products_landed_cost_non_negative check (landed_cost_amount >= 0),
    constraint ck_products_sell_non_negative        check (sell_amount >= 0),
    constraint ck_products_price_per_kg_non_negative
        check (price_per_kg_amount is null or price_per_kg_amount >= 0)
);

-- FR-055 — SKU unique per tenant, case-insensitive, among live rows.
create unique index uq_products_sku_ci on products (lower(sku)) where deleted_at is null;
-- FR-283 / AC-270-2 — PLU unique per live product, company-wide.
create unique index uq_products_plu on products (plu) where deleted_at is null and plu is not null;
create index ix_products_category on products (category_id);
create index ix_products_uom on products (uom_id);

-- ---------------------------------------------------------------------
-- ENT-011a ProductVariant
-- ---------------------------------------------------------------------
create table product_variants (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    parent_product_id   bigint       not null references products (id) on delete cascade,
    sku                 varchar(50)  not null,
    attributes          jsonb        not null default '{}'::jsonb,

    cost_amount         bigint       not null default 0,
    cost_currency       char(3)      not null,
    po_cost_amount      bigint       not null default 0,
    landed_cost_amount  bigint       not null default 0,
    sell_amount         bigint       not null default 0,
    sell_currency       char(3)      not null,
    tax_code_id         char(26),                                    -- loose cross-slice ref

    image_keys          jsonb        not null default '[]'::jsonb,

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint ck_product_variants_cost_non_negative        check (cost_amount >= 0),
    constraint ck_product_variants_po_cost_non_negative     check (po_cost_amount >= 0),
    constraint ck_product_variants_landed_cost_non_negative check (landed_cost_amount >= 0),
    constraint ck_product_variants_sell_non_negative        check (sell_amount >= 0)
);

create unique index uq_product_variants_sku_ci
    on product_variants (lower(sku)) where deleted_at is null;
create index ix_product_variants_parent on product_variants (parent_product_id);

-- ---------------------------------------------------------------------
-- ENT-011b ProductBarcode
-- ---------------------------------------------------------------------
create table product_barcodes (
    id              bigint generated by default as identity primary key,
    public_id       char(26)      not null unique,

    product_id      bigint        not null references products (id) on delete cascade,
    variant_id      bigint        references product_variants (id) on delete cascade,
    barcode         varchar(64)   not null,
    is_primary      boolean       not null default false,
    format          varchar(16)   not null,
    qty_per_scan    numeric(18,6) not null default 1,
    source          varchar(16)   not null default 'manufacturer',
    plu_code        varchar(10),

    created_at      timestamptz   not null default now(),
    created_by      char(26),
    updated_at      timestamptz   not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint        not null default 0,

    constraint uq_product_barcodes_barcode unique (barcode),
    constraint ck_product_barcodes_format
        check (format in ('EAN13','UPCA','CODE128','WEIGHTED','PLU','OTHER')),
    constraint ck_product_barcodes_source
        check (source in ('manufacturer','generated'))
);

create index ix_product_barcodes_product on product_barcodes (product_id);
create index ix_product_barcodes_variant on product_barcodes (variant_id);
-- AC-012-3 — at most one primary barcode per product.
create unique index uq_product_barcodes_one_primary
    on product_barcodes (product_id) where is_primary = true;
-- Partial unique on PLU code (only when set).
create unique index uq_product_barcodes_plu
    on product_barcodes (plu_code) where plu_code is not null;

-- ---------------------------------------------------------------------
-- ENT-011c ProductImage
-- ---------------------------------------------------------------------
create table product_images (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    product_id      bigint       not null references products (id) on delete cascade,
    file_id         varchar(80)  not null,
    position        integer      not null default 0,
    bytes           bigint       not null default 0,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint uq_product_images_position unique (product_id, position),
    constraint ck_product_images_bytes_non_negative check (bytes >= 0)
);

create index ix_product_images_product on product_images (product_id);

-- ---------------------------------------------------------------------
-- ENT-012 CustomAttributeValue
-- ---------------------------------------------------------------------
create table product_custom_attribute_values (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    product_id      bigint       not null references products (id) on delete cascade,
    variant_id      bigint       references product_variants (id) on delete cascade,
    scope           varchar(16)  not null default 'product',
    key             varchar(100) not null,
    value           text,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint uq_product_custom_attribute_values_key
        unique (product_id, variant_id, scope, key),
    constraint ck_product_custom_attribute_values_scope
        check (scope in ('product','variant'))
);

create index ix_product_custom_attribute_values_product
    on product_custom_attribute_values (product_id);
create index ix_product_custom_attribute_values_variant
    on product_custom_attribute_values (variant_id);

-- =====================================================================
-- Permissions for the catalog slice (product.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM2x ULIDs — no collision with the seeded PERMxx / ROLE01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM20', 'product.product.read',         'View products',          'product', 'List and view products'),
  ('01J0AA000000000000PERM21', 'product.product.write',        'Manage products',        'product', 'Create, update, delete products and move lifecycle state'),
  ('01J0AA000000000000PERM22', 'product.variant.read',         'View variants',          'product', 'List and view product variants'),
  ('01J0AA000000000000PERM23', 'product.variant.write',        'Manage variants',        'product', 'Create, update, and delete product variants'),
  ('01J0AA000000000000PERM24', 'product.barcode.read',         'View barcodes',          'product', 'List, view, and look up product barcodes'),
  ('01J0AA000000000000PERM25', 'product.barcode.write',        'Manage barcodes',        'product', 'Create, set-primary, and delete product barcodes'),
  ('01J0AA000000000000PERM26', 'product.image.read',           'View product images',    'product', 'List and view product images'),
  ('01J0AA000000000000PERM27', 'product.image.write',          'Manage product images',  'product', 'Add and delete product images'),
  ('01J0AA000000000000PERM28', 'product.customattribute.read', 'View custom attributes', 'product', 'List and view product custom attribute values'),
  ('01J0AA000000000000PERM29', 'product.customattribute.write','Manage custom attributes','product', 'Upsert and delete product custom attribute values');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'product.product.read', 'product.product.write',
    'product.variant.read', 'product.variant.write',
    'product.barcode.read', 'product.barcode.write',
    'product.image.read', 'product.image.write',
    'product.customattribute.read', 'product.customattribute.write')
where r.code = 'admin';
