-- =====================================================================
-- V21 — PRODUCT module, pricing sub-slice (US-013 / FR-061..064).
--
-- Mirrors the JPA entities under
-- com.springboot.erp.modules.product.pricing.domain, each extending BaseEntity
-- (public_id, created_at/by, updated_at/by, deleted_at, version). Money is
-- long minor units (price_amount) + ISO-4217 char(3) (price_currency).
--
-- Cross-slice references (company, product, variant, location) are held by
-- ULID public_id char(26) with NO database FK — resolved at the application
-- layer, per the vertical-slice convention. The only in-slice FK is
-- price_list_items.price_list_id -> price_lists(id).
--
-- Reproduces the reference unique/check constraints and indexes from
-- app/products/models.py (PriceList, PriceListItem, PriceHistory,
-- ProductLocationOverride) and seeds this slice's permission codes granted
-- to the admin role (following V10__currency.sql).
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-013 PriceList
-- ---------------------------------------------------------------------
create table price_lists (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    company_id          char(26)     not null,       -- cross-slice ref (no FK)
    name                varchar(100) not null,
    currency            char(3)      not null,
    status              varchar(16)  not null default 'active',
    price_display_mode  varchar(16),

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_price_lists_company_name unique (company_id, name),
    constraint ck_price_lists_status check (status in ('active', 'inactive'))
);

-- ---------------------------------------------------------------------
-- ENT-013a PriceListItem
-- ---------------------------------------------------------------------
create table price_list_items (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    price_list_id   bigint       not null
                        references price_lists (id) on delete cascade,
    product_id      char(26)     not null,           -- cross-slice ref (no FK)
    variant_id      char(26),                        -- cross-slice ref (no FK)
    price_amount    bigint       not null,
    price_currency  char(3)      not null,
    effective_from  timestamptz  not null default now(),
    effective_to    timestamptz,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint ck_price_list_items_price_non_negative check (price_amount >= 0),
    constraint ck_price_list_items_effective_range
        check (effective_to is null or effective_to > effective_from)
);

create index ix_price_list_items_price_list on price_list_items (price_list_id);
create index ix_price_list_items_product on price_list_items (product_id);
create index ix_price_list_items_variant on price_list_items (variant_id);
-- Reference lookup index (price_list_id, product_id, variant_id, effective_from).
create index ix_price_list_items_lookup
    on price_list_items (price_list_id, product_id, variant_id, effective_from);

-- ---------------------------------------------------------------------
-- PriceHistory (FR-064) — append-only ledger of base-price changes.
-- ---------------------------------------------------------------------
create table product_price_history (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    product_id      char(26)     not null,           -- cross-slice ref (no FK)
    variant_id      char(26),                        -- cross-slice ref (no FK)
    field           varchar(20)  not null,
    old_amount      bigint,
    new_amount      bigint       not null,
    currency        char(3)      not null,
    effective_from  timestamptz  not null default now(),
    changed_at      timestamptz  not null default now(),
    changed_by      char(26),

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint ck_product_price_history_field check (field in ('cost', 'sell'))
);

create index ix_product_price_history_product on product_price_history (product_id);
create index ix_product_price_history_variant on product_price_history (variant_id);
create index ix_product_price_history_effective_from
    on product_price_history (effective_from);

-- ---------------------------------------------------------------------
-- ENT-013b ProductLocationOverride (FR-063)
-- ---------------------------------------------------------------------
create table product_location_overrides (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    product_id      char(26)     not null,           -- cross-slice ref (no FK)
    location_id     char(26)     not null,           -- cross-slice ref (no FK)
    variant_id      char(26),                        -- cross-slice ref (no FK)
    price_amount    bigint       not null,
    price_currency  char(3)      not null,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint ck_product_location_overrides_price_non_negative
        check (price_amount >= 0)
);

create index ix_product_location_overrides_product on product_location_overrides (product_id);
create index ix_product_location_overrides_location on product_location_overrides (location_id);
create index ix_product_location_overrides_variant on product_location_overrides (variant_id);

-- Partial unique: one live override per (product, location, variant). Postgres
-- has no declarative partial-unique constraint, so it lives in the DDL. NULL
-- variant_id rows are treated as distinct by the null-coalesced expression so
-- the "no-variant" override is still unique per (product, location).
create unique index uq_product_location_override
    on product_location_overrides (product_id, location_id, coalesce(variant_id, ''))
    where deleted_at is null;

-- ---------------------------------------------------------------------
-- Permissions for the pricing slice (product.<concept>.read/write), granted
-- to the admin role so the @PreAuthorize checks are reachable. Follows the
-- convention seeded in V10__currency.sql. Pricing uses the PERM3x band; the
-- catalog slice uses PERM2x and promotions PERM4x, so these do not collide
-- with the existing 01J0AA000000000000PERMxx / ...ROLE01 seeds.
-- ---------------------------------------------------------------------
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM30', 'product.pricelist.read',        'View price lists',        'product', 'List and view price lists and their items'),
  ('01J0AA000000000000PERM31', 'product.pricelist.write',       'Manage price lists',      'product', 'Create, update, delete price lists and upsert/patch/delete their items'),
  ('01J0AA000000000000PERM32', 'product.pricehistory.read',     'View price history',      'product', 'List a product''s append-only price history'),
  ('01J0AA000000000000PERM33', 'product.pricehistory.write',    'Schedule price changes',  'product', 'Append a scheduled future base-price change'),
  ('01J0AA000000000000PERM34', 'product.locationoverride.read', 'View location overrides', 'product', 'List and view per-location price overrides'),
  ('01J0AA000000000000PERM35', 'product.locationoverride.write','Manage location overrides','product', 'Upsert and delete per-location price overrides');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'product.pricelist.read',
    'product.pricelist.write',
    'product.pricehistory.read',
    'product.pricehistory.write',
    'product.locationoverride.read',
    'product.locationoverride.write')
where r.code = 'admin';
