-- =====================================================================
-- V22 — PRODUCT module, "promotions" sub-slice (US-014 / US-015).
--
-- Entities (all extend BaseEntity → public_id / created_at,by / updated_at,by
-- / deleted_at / version):
--   * promotions                     ENT-014 Promotion (FR-065..069)
--   * reason_codes                   Discount reason-code master (FR-068)
--   * product_lifecycle_transitions  Append-only lifecycle ledger (FR-074)
--
-- Cross-slice references (company_id, product_id, changed_by) are stored as
-- loose char(26) ULIDs — no hard FK across slices (app-layer resolution).
-- Check constraints reproduce the reference SQLAlchemy models exactly.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-014 Promotion
-- ---------------------------------------------------------------------
create table promotions (
    id               bigint generated by default as identity primary key,
    public_id        char(26)     not null unique,

    company_id       char(26)     not null,          -- owning company ULID (no hard FK)
    name             varchar(200) not null,
    type             varchar(20)  not null,
    config           jsonb        not null default '{}'::jsonb,
    scope            jsonb        not null default '{}'::jsonb,
    segment_id       char(26),
    date_from        timestamptz  not null,
    date_to          timestamptz  not null,
    stackable        boolean      not null default false,
    reason_required  boolean      not null default false,
    status           varchar(16)  not null default 'DRAFT',

    created_at       timestamptz  not null default now(),
    created_by       char(26),
    updated_at       timestamptz  not null default now(),
    updated_by       char(26),
    deleted_at       timestamptz,
    version          bigint       not null default 0,

    constraint ck_promotions_type
        check (type in ('PERCENT','FIXED','BUY_X_GET_Y','SPEND_THRESHOLD')),
    constraint ck_promotions_status
        check (status in ('DRAFT','ACTIVE','PAUSED','EXPIRED')),
    constraint ck_promotions_date_range
        check (date_to > date_from)
);

create index ix_promotions_company on promotions (company_id) where deleted_at is null;
-- Name is unique per company among live rows (case-insensitive) — enforced in
-- the service; this partial unique index backstops the invariant.
create unique index uq_promotions_company_name_ci
    on promotions (company_id, lower(name))
    where deleted_at is null;

-- ---------------------------------------------------------------------
-- Discount reason-code master (FR-068)
-- ---------------------------------------------------------------------
create table reason_codes (
    id               bigint generated by default as identity primary key,
    public_id        char(26)     not null unique,

    code             varchar(50)  not null,          -- immutable after creation
    label            varchar(200) not null,
    description      text,
    is_active        boolean      not null default true,

    created_at       timestamptz  not null default now(),
    created_by       char(26),
    updated_at       timestamptz  not null default now(),
    updated_by       char(26),
    deleted_at       timestamptz,
    version          bigint       not null default 0
);

create index ix_reason_codes_code on reason_codes (code);
-- code unique among live (non-deleted) rows, case-insensitive (FR-068) — a
-- soft-deleted code can be re-introduced later.
create unique index uq_reason_codes_code_ci
    on reason_codes (lower(code))
    where deleted_at is null;

-- ---------------------------------------------------------------------
-- Append-only product lifecycle transition ledger (FR-074)
-- ---------------------------------------------------------------------
create table product_lifecycle_transitions (
    id               bigint generated by default as identity primary key,
    public_id        char(26)     not null unique,

    product_id       char(26)     not null,          -- product ULID (no hard FK)
    from_state       varchar(16)  not null,
    to_state         varchar(16)  not null,
    reason           varchar(500),
    changed_at       timestamptz  not null default now(),
    changed_by       char(26),                       -- acting user ULID (no hard FK)

    created_at       timestamptz  not null default now(),
    created_by       char(26),
    updated_at       timestamptz  not null default now(),
    updated_by       char(26),
    deleted_at       timestamptz,
    version          bigint       not null default 0,

    constraint ck_lifecycle_transitions_from_state
        check (from_state in ('DRAFT','ACTIVE','ON_HOLD','RUN_OUT','DISCONTINUED')),
    constraint ck_lifecycle_transitions_to_state
        check (to_state in ('DRAFT','ACTIVE','ON_HOLD','RUN_OUT','DISCONTINUED'))
);

create index ix_lifecycle_transitions_product
    on product_lifecycle_transitions (product_id, changed_at desc);

-- ---------------------------------------------------------------------
-- Permissions for this slice (product.<concept>.read/.write), granted to the
-- admin role so the @PreAuthorize checks are reachable (mirrors V10 currency).
-- Promotions sub-slice owns the PERM4x band.
-- ---------------------------------------------------------------------
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM41', 'product.promotion.read',   'View promotions',    'product', 'List and view promotions'),
  ('01J0AA000000000000PERM42', 'product.promotion.write',  'Manage promotions',  'product', 'Create, update, delete, and change status of promotions'),
  ('01J0AA000000000000PERM43', 'product.reasoncode.read',  'View reason codes',  'product', 'List and view discount reason codes'),
  ('01J0AA000000000000PERM44', 'product.reasoncode.write', 'Manage reason codes','product', 'Create, update, and delete discount reason codes'),
  ('01J0AA000000000000PERM45', 'product.lifecycle.read',   'View lifecycle log', 'product', 'View product lifecycle transition history'),
  ('01J0AA000000000000PERM46', 'product.lifecycle.write',  'Change lifecycle',   'product', 'Record product lifecycle state transitions');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'product.promotion.read', 'product.promotion.write',
    'product.reasoncode.read', 'product.reasoncode.write',
    'product.lifecycle.read', 'product.lifecycle.write')
where r.code = 'admin';
