-- =====================================================================
-- V30 — INVENTORY module, "stock" sub-slice (the core stock engine).
--
-- Matches the JPA entities under
-- com.guru.erp.modules.inventory.stock.domain extending BaseEntity:
--   ENT-040 StockLedger              (append-only movement ledger)
--   ENT-041 InventoryValuationConfig (per-company FIFO/AVG/STANDARD)
--   ENT-045 ProductBatch             (batch/lot tracking with expiry)
--
-- On-hand / availability / valuation are pure read projections over the
-- ledger — no materialised table. Quantities are numeric(18,6) fixed
-- precision (never float); money is bigint minor units + char(3) currency.
--
-- Cross-slice references (product, variant, location, company, batch, actor
-- user, source doc) are held as loose ULID char(26) columns — no hard
-- cross-slice FK, per the vertical-slice rule. All constraints, unique
-- indexes and covering indexes are reproduced from the reference model.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-040 StockLedger — append-only (FR-114 / FR-118)
-- ---------------------------------------------------------------------
create table stock_ledger (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    occurred_at         timestamptz   not null default now(),
    product_id          char(26)      not null,            -- loose cross-slice ref
    variant_id          char(26),                          -- loose cross-slice ref
    location_id         char(26)      not null,            -- loose cross-slice ref
    status              varchar(15)   not null default 'AVAILABLE',
    movement_type       varchar(15)   not null,
    qty_signed          numeric(18,6) not null,
    unit_cost_amount    bigint        not null default 0,
    unit_cost_currency  char(3)       not null default 'USD',
    -- Value-only revaluation delta (minor units, base currency). Non-zero only
    -- on REVALUATION rows, which carry qty_signed = 0 so on-hand quantity is
    -- untouched while inventory value shifts to the latest approved bill cost.
    value_delta_amount  bigint        not null default 0,
    source_doc_type     varchar(20)   not null,
    source_doc_id       char(26)      not null,
    expiry_date         timestamptz,
    batch_id            char(26),                          -- loose ref to product_batches.public_id
    actor_user_id       char(26),                          -- loose ref to users

    notes               varchar(500),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_stock_ledger_status
        check (status in ('AVAILABLE','RESERVED','QUARANTINE','IN_TRANSIT'))
);

create index ix_stock_ledger_product_location_occurred
    on stock_ledger (product_id, location_id, occurred_at);
create index ix_stock_ledger_source_doc
    on stock_ledger (source_doc_type, source_doc_id);
-- Covers the correlated source-doc + product + movement_type lookups.
create index ix_stock_ledger_src_product_move
    on stock_ledger (source_doc_type, source_doc_id, product_id, movement_type);

-- ---------------------------------------------------------------------
-- ENT-041 InventoryValuationConfig — one row per company (FR-116)
-- ---------------------------------------------------------------------
create table inventory_valuation_configs (
    id              bigint generated by default as identity primary key,
    public_id       char(26)     not null unique,

    company_id      char(26)     not null,                 -- loose cross-slice ref
    method          varchar(20)  not null default 'MOVING_AVERAGE',
    locked          boolean      not null default false,

    created_at      timestamptz  not null default now(),
    created_by      char(26),
    updated_at      timestamptz  not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint       not null default 0,

    constraint uq_valuation_config_company unique (company_id),
    constraint ck_valuation_config_method
        check (method in ('MOVING_AVERAGE','FIFO','STANDARD'))
);

-- ---------------------------------------------------------------------
-- ENT-045 ProductBatch — batch/lot with barcode + pricing + expiry
-- ---------------------------------------------------------------------
create table product_batches (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    product_id          char(26)      not null,            -- loose cross-slice ref
    variant_id          char(26),                          -- loose cross-slice ref
    source_doc_type     varchar(20)   not null,
    source_doc_id       varchar(50)   not null,

    batch_no            varchar(100),
    barcode             varchar(64),                       -- null for WEIGHTED
    barcode_format      varchar(16)   not null,
    barcode_source      varchar(16)   not null default 'manufacturer',
    qty_per_scan        numeric(18,6) not null default 1,

    grn_cost_amount     bigint        not null default 0,
    grn_cost_currency   char(3)       not null default 'USD',
    mrp_amount          bigint,
    mrp_currency        char(3),
    sell_price_amount   bigint,
    sell_price_currency char(3),

    qty_received        numeric(18,6) not null default 0,
    manufacture_date    timestamptz,
    expiry_date         timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_product_batches_barcode_format
        check (barcode_format in ('EAN13','UPCA','CODE128','WEIGHTED','PLU','OTHER')),
    constraint ck_product_batches_source
        check (barcode_source in ('manufacturer','generated'))
);

-- Partial unique: two batches may both have barcode=NULL (WEIGHTED),
-- but no two batches may share the same non-NULL barcode value.
create unique index uq_product_batches_barcode
    on product_batches (barcode) where barcode is not null;
create index ix_product_batches_source
    on product_batches (source_doc_type, source_doc_id);
create index ix_product_batches_expiry
    on product_batches (expiry_date) where expiry_date is not null;

-- =====================================================================
-- Permissions for the inventory "stock" slice (inventory.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM5x ULIDs — no collision with the seeded PERMxx / ROLE01 set
-- (existing run up to the product slices' PERM4x).
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM50', 'inventory.stock.read',      'View stock on hand',      'inventory', 'View on-hand, availability, and per-product stock summaries'),
  ('01J0AA000000000000PERM51', 'inventory.stock.write',     'Adjust stock',            'inventory', 'Reserved for stock mutations in the stock engine'),
  ('01J0AA000000000000PERM52', 'inventory.ledger.read',     'View stock ledger',       'inventory', 'List and filter append-only stock ledger entries'),
  ('01J0AA000000000000PERM53', 'inventory.ledger.write',    'Post stock movements',    'inventory', 'Append movement rows to the stock ledger'),
  ('01J0AA000000000000PERM54', 'inventory.valuation.read',  'View valuation config',   'inventory', 'View the per-company inventory valuation method'),
  ('01J0AA000000000000PERM55', 'inventory.valuation.write', 'Manage valuation config', 'inventory', 'Set the per-company inventory valuation method'),
  ('01J0AA000000000000PERM56', 'inventory.batch.read',      'View product batches',    'inventory', 'List, view, and look up product batches by barcode'),
  ('01J0AA000000000000PERM57', 'inventory.batch.write',     'Manage product batches',  'inventory', 'Create, update, and delete product batches');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'inventory.stock.read', 'inventory.stock.write',
    'inventory.ledger.read', 'inventory.ledger.write',
    'inventory.valuation.read', 'inventory.valuation.write',
    'inventory.batch.read', 'inventory.batch.write')
where r.code = 'admin';
