-- =====================================================================
-- V31 — INVENTORY module, "movements" sub-slice (US-023 / US-024).
--
-- Stock movements: StockTransfer + lines (move stock between locations,
-- workflow Draft → Approved → Partially Complete/Complete) and
-- StockAdjustment + lines (correct stock with a reason code, workflow
-- Draft → Pending Approval/Approved → Posted → Reversed).
--
-- Matches the JPA entities under
-- com.guru.erp.modules.inventory.movements.domain extending BaseEntity.
--
-- Cross-slice references (locations, products, uoms, variants, GL accounts,
-- journal entries, approver users) are held as loose ULID char(26) columns
-- — no hard cross-slice FK (app-layer resolution per the vertical-slice rule).
-- Same-slice references (line → header) are real FKs. Posting emits outbox
-- events (inventory.transfer.*, inventory.adjustment.*) consumed by the stock
-- and finance slices — no ledger table is written here.
--
-- Status columns store the human wire label ('Draft', 'Approved', …) via the
-- entity AttributeConverters, guarded by check constraints below.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-042 StockTransfer
-- ---------------------------------------------------------------------
create table stock_transfers (
    id                      bigint generated by default as identity primary key,
    public_id               char(26)     not null unique,

    number                  varchar(30)  not null,
    source_location_id      char(26)     not null,        -- loose cross-slice ref
    destination_location_id char(26)     not null,        -- loose cross-slice ref
    status                  varchar(15)  not null default 'Draft',
    notes                   text,
    transfer_date           date,
    confirmed_at            timestamptz,
    received_at             timestamptz,

    created_at              timestamptz  not null default now(),
    created_by              char(26),
    updated_at              timestamptz  not null default now(),
    updated_by              char(26),
    deleted_at              timestamptz,
    version                 bigint       not null default 0,

    constraint uq_stock_transfers_number unique (number),
    constraint ck_transfers_different_locations
        check (source_location_id <> destination_location_id),
    constraint ck_stock_transfers_status
        check (status in ('Draft','Approved','Partially Complete','Complete'))
);

-- Filter keys: status (equality) + created_at (range).
create index ix_stock_transfers_status_created_at on stock_transfers (status, created_at);
create index ix_stock_transfers_source on stock_transfers (source_location_id);
create index ix_stock_transfers_destination on stock_transfers (destination_location_id);

-- ---------------------------------------------------------------------
-- ENT-042a StockTransferLine
-- ---------------------------------------------------------------------
create table stock_transfer_lines (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    transfer_id         bigint        not null references stock_transfers (id) on delete cascade,
    line_no             integer       not null,
    product_id          char(26)      not null,           -- loose cross-slice ref
    uom_id              char(26),                          -- loose cross-slice ref
    variant_id          char(26),                          -- loose cross-slice ref
    qty_sent            numeric(18,6) not null,
    qty_received        numeric(18,6) not null default 0,
    qty_short           numeric(18,6) not null default 0,
    qty_damaged         numeric(18,6) not null default 0,
    discrepancy_reason  varchar(500),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_transfer_lines_transfer_line unique (transfer_id, line_no),
    constraint ck_transfer_lines_qty_sent_positive          check (qty_sent > 0),
    constraint ck_transfer_lines_qty_received_non_negative  check (qty_received >= 0),
    constraint ck_transfer_lines_qty_short_non_negative     check (qty_short >= 0),
    constraint ck_transfer_lines_qty_damaged_non_negative   check (qty_damaged >= 0)
);

create index ix_stock_transfer_lines_transfer on stock_transfer_lines (transfer_id);
create index ix_stock_transfer_lines_product on stock_transfer_lines (product_id);
create index ix_stock_transfer_lines_variant on stock_transfer_lines (variant_id);

-- ---------------------------------------------------------------------
-- ENT-043 StockAdjustment
-- ---------------------------------------------------------------------
create table stock_adjustments (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    number              varchar(30)  not null,
    location_id         char(26)     not null,            -- loose cross-slice ref
    reason              varchar(200) not null,
    notes               text,
    status              varchar(20)  not null default 'Draft',
    threshold_exceeded  boolean      not null default false,
    approver_id         char(26),                          -- loose cross-slice ref (user)
    approved_at         timestamptz,
    posted_at           timestamptz,
    variance_account_id char(26),                          -- loose cross-slice ref (GL account)
    journal_entry_id    char(26),                          -- loose cross-slice ref (GL journal)

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_stock_adjustments_number unique (number),
    constraint ck_stock_adjustments_status
        check (status in ('Draft','Pending Approval','Approved','Posted','Reversed'))
);

-- Composite covers the common filter pattern: branch + status + date range.
create index ix_stock_adjustments_location_status_created_at
    on stock_adjustments (location_id, status, created_at);

-- ---------------------------------------------------------------------
-- ENT-043a StockAdjustmentLine
-- ---------------------------------------------------------------------
create table stock_adjustment_lines (
    id                      bigint generated by default as identity primary key,
    public_id               char(26)      not null unique,

    adjustment_id           bigint        not null references stock_adjustments (id) on delete cascade,
    line_no                 integer       not null,
    product_id              char(26)      not null,        -- loose cross-slice ref
    uom_id                  char(26),                       -- loose cross-slice ref
    variant_id              char(26),                       -- loose cross-slice ref
    variant_name            varchar(500),
    qty_counted             numeric(18,6) not null,
    qty_on_hand_at_count    numeric(18,6) not null default 0,
    qty_variance            numeric(18,6) not null default 0,
    write_off_reason        varchar(200),
    unit_cost_amount        bigint        not null default 0,
    unit_cost_currency      char(3)       not null default 'USD',

    created_at              timestamptz   not null default now(),
    created_by              char(26),
    updated_at              timestamptz   not null default now(),
    updated_by              char(26),
    deleted_at              timestamptz,
    version                 bigint        not null default 0,

    constraint uq_adjustment_lines_adj_line unique (adjustment_id, line_no),
    constraint ck_adjustment_lines_qty_counted_non_negative check (qty_counted >= 0)
);

create index ix_stock_adjustment_lines_adjustment on stock_adjustment_lines (adjustment_id);
create index ix_stock_adjustment_lines_product on stock_adjustment_lines (product_id);
create index ix_stock_adjustment_lines_variant on stock_adjustment_lines (variant_id);

-- =====================================================================
-- Permissions for the movements slice (inventory.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM6x ULIDs — no collision with the seeded PERMxx / ROLE01 set
-- (existing run up through the product slices, PERM01–46).
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM60', 'inventory.transfer.read',    'View stock transfers',   'inventory', 'List and view stock transfers'),
  ('01J0AA000000000000PERM61', 'inventory.transfer.write',   'Manage stock transfers', 'inventory', 'Create, update, delete, confirm, receive, and complete stock transfers'),
  ('01J0AA000000000000PERM62', 'inventory.adjustment.read',  'View stock adjustments', 'inventory', 'List and view stock adjustments'),
  ('01J0AA000000000000PERM63', 'inventory.adjustment.write', 'Manage stock adjustments','inventory', 'Create, update, delete, approve, and post stock adjustments');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'inventory.transfer.read', 'inventory.transfer.write',
    'inventory.adjustment.read', 'inventory.adjustment.write')
where r.code = 'admin';
