-- =====================================================================
-- V32 — INVENTORY module, "counts" sub-slice (governance + setup).
--
-- Entities (matching com.springboot.erp.modules.inventory.counts.domain,
-- each extending BaseEntity):
--   ENT-044  CycleCountPlan          — physical count plan header
--   ENT-044a CycleCountLine          — counted lines (variance vs system qty)
--   ENT-045  StockOpening            — opening balances at go-live
--   ENT-046  BarcodeNomenclatureRule — parse rules for weighted/priced barcodes
--
-- Cross-slice references (company, product, variant, location, gl account,
-- posted_by user) are held as loose ULID char(26) columns — no hard cross-slice
-- FK (app-layer resolution per the vertical-slice rule). The header->line
-- reference (cycle_count_lines.plan_id -> cycle_count_plans.id) is same-slice,
-- so it is a real FK. On approval / post the reference app also writes ledger +
-- journal rows; here those are emitted as outbox events (documented in the
-- services), so no ledger/finance FK is reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-044 CycleCountPlan
-- ---------------------------------------------------------------------
create table cycle_count_plans (
    id            bigint generated by default as identity primary key,
    public_id     char(26)     not null unique,

    number        varchar(30)  not null,
    location_id   char(26)     not null,           -- loose cross-slice ref
    scope         varchar(10)  not null default 'ALL',
    scope_config  jsonb,
    planned_date  timestamptz  not null,
    status        varchar(15)  not null default 'Draft',
    accuracy_pct  numeric(5, 2),
    notes         text,

    created_at    timestamptz  not null default now(),
    created_by    char(26),
    updated_at    timestamptz  not null default now(),
    updated_by    char(26),
    deleted_at    timestamptz,
    version       bigint       not null default 0,

    constraint uq_cycle_count_plans_number unique (number),
    constraint ck_cycle_count_plans_scope
        check (scope in ('ALL', 'CATEGORY', 'ABC', 'MANUAL')),
    constraint ck_cycle_count_plans_status
        check (status in ('Draft', 'In Progress', 'Completed', 'Approved'))
);

create index ix_cycle_count_plans_location on cycle_count_plans (location_id);

-- ---------------------------------------------------------------------
-- ENT-044a CycleCountLine
-- ---------------------------------------------------------------------
create table cycle_count_lines (
    id                bigint generated by default as identity primary key,
    public_id         char(26)      not null unique,

    plan_id           bigint        not null
                          references cycle_count_plans (id) on delete cascade,
    line_no           integer       not null,
    product_id        char(26)      not null,       -- loose cross-slice ref
    qty_expected      numeric(18, 6) not null default 0,
    qty_first_pass    numeric(18, 6),
    qty_second_pass   numeric(18, 6),
    variance          numeric(18, 6) not null default 0,
    requires_recount  boolean       not null default false,

    created_at        timestamptz   not null default now(),
    created_by        char(26),
    updated_at        timestamptz   not null default now(),
    updated_by        char(26),
    deleted_at        timestamptz,
    version           bigint        not null default 0,

    constraint uq_cycle_count_lines_plan_line unique (plan_id, line_no),
    constraint ck_cycle_count_lines_qty_expected_non_negative
        check (qty_expected >= 0)
);

create index ix_cycle_count_lines_plan on cycle_count_lines (plan_id);
create index ix_cycle_count_lines_product on cycle_count_lines (product_id);

-- ---------------------------------------------------------------------
-- ENT-045 StockOpening  (table: stock_opening_entries)
-- ---------------------------------------------------------------------
create table stock_opening_entries (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,     -- loose cross-slice ref
    product_id          char(26)      not null,     -- loose cross-slice ref
    variant_id          char(26),                   -- loose cross-slice ref (nullable)
    location_id         char(26)      not null,     -- loose cross-slice ref

    opening_qty         numeric(18, 6) not null,
    unit_cost_amount    bigint        not null default 0,
    unit_cost_currency  char(3)       not null default 'USD',
    gl_account_id       char(26)      not null,     -- loose cross-slice ref (counter account)
    notes               varchar(500),

    status              varchar(20)   not null default 'Draft',
    posted_at           timestamptz,
    posted_by           char(26),                   -- loose cross-slice ref (user)
    journal_entry_id    char(26),                   -- loose cross-slice ref (JE, set post-time)

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_stock_opening_status
        check (status in ('Draft', 'Posted')),
    constraint ck_stock_opening_qty_nonneg check (opening_qty >= 0),
    constraint ck_stock_opening_cost_nonneg check (unit_cost_amount >= 0)
);

create index ix_stock_opening_company on stock_opening_entries (company_id);
create index ix_stock_opening_product on stock_opening_entries (product_id);
create index ix_stock_opening_location on stock_opening_entries (location_id);

-- Partial unique: at most one LIVE opening (Draft OR Posted) per
-- (company, product, variant, location). coalesce(variant_id, '0') keeps the
-- guard working for non-variant products (Postgres treats NULLs as distinct
-- otherwise). Only deleted_at IS NULL rows count — a soft-deleted opening frees
-- the key for a legitimate re-open. Mirrors the reference partial unique index.
create unique index uq_stock_opening_company_product_variant_location
    on stock_opening_entries (company_id, product_id, coalesce(variant_id, '0'), location_id)
    where deleted_at is null;

-- ---------------------------------------------------------------------
-- ENT-046 BarcodeNomenclatureRule
-- ---------------------------------------------------------------------
create table barcode_nomenclature_rules (
    id              bigint generated by default as identity primary key,
    public_id       char(26)      not null unique,

    company_id      char(26)      not null,         -- loose cross-slice ref
    name            varchar(100)  not null,
    prefix          varchar(4)    not null,
    rule_type       varchar(20)   not null,
    item_digits     integer       not null default 5,
    measure_digits  integer       not null default 5,
    measure_scale   numeric(10, 6) not null default 0.001,
    is_active       boolean       not null default true,

    created_at      timestamptz   not null default now(),
    created_by      char(26),
    updated_at      timestamptz   not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint        not null default 0,

    constraint ck_barcode_nomenclature_rule_type
        check (rule_type in ('weighted_qty', 'weighted_price'))
);

create index ix_barcode_nomenclature_rules_company on barcode_nomenclature_rules (company_id);

-- ---------------------------------------------------------------------
-- Permissions — inventory.<concept>.read/.write for each aggregate, granted to
-- the admin role (mirrors V10 / V20). Without these rows the @PreAuthorize
-- checks would always 403. Fresh PERM7x ULIDs — no collision with the seeded
-- PERMxx set (up through the product slices) or ROLE01.
-- ---------------------------------------------------------------------
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM70', 'inventory.cyclecount.read',  'View cycle counts',   'inventory', 'List and view cycle count plans and their counted lines'),
  ('01J0AA000000000000PERM71', 'inventory.cyclecount.write', 'Manage cycle counts', 'inventory', 'Create cycle count plans, submit passes, and approve/post variances'),
  ('01J0AA000000000000PERM72', 'inventory.opening.read',     'View stock openings', 'inventory', 'List and view opening balance entries'),
  ('01J0AA000000000000PERM73', 'inventory.opening.write',    'Manage stock openings','inventory', 'Create, update, post, and delete opening balance entries'),
  ('01J0AA000000000000PERM74', 'inventory.barcoderule.read', 'View barcode rules',  'inventory', 'List and view barcode nomenclature (weighted/priced) rules'),
  ('01J0AA000000000000PERM75', 'inventory.barcoderule.write','Manage barcode rules','inventory', 'Create, update, and delete barcode nomenclature rules');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'inventory.cyclecount.read',
    'inventory.cyclecount.write',
    'inventory.opening.read',
    'inventory.opening.write',
    'inventory.barcoderule.read',
    'inventory.barcoderule.write'
)
where r.code = 'admin';
