-- =====================================================================
-- V40 — PROCUREMENT module, "suppliers" sub-slice (the AP master).
--
-- Matches the JPA entities under
-- com.springboot.erp.modules.procurement.suppliers.domain extending BaseEntity:
--   ENT-026  Supplier            (AP master: contact/address/bank jsonb,
--                                 trade type, status lifecycle, credit
--                                 limit + opening balance as Money)
--   ENT-026a SupplierAttachment  (supporting documents per supplier)
--
-- Money is bigint minor units + char(3) currency; the opening-balance FX
-- rate is numeric(18,6). Cross-slice references (location, opening-balance
-- GL account, uploading user) are held as loose ULID char(26) columns — no
-- hard cross-slice FK, per the vertical-slice rule. The attachment→supplier
-- link IS same-slice, so it keeps a real FK. Check constraints, the unique
-- code, and the supplier-id index are reproduced from the reference model.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-026 Supplier — US-016 / FR-075–079
-- ---------------------------------------------------------------------
create table suppliers (
    id                              bigint        generated by default as identity primary key,
    public_id                       char(26)      not null unique,

    code                            varchar(20)   not null unique,
    name                            varchar(200)  not null,
    type                            varchar(10)   not null default 'BOTH',
    contact                         jsonb,
    address                         jsonb,
    payment_terms                   varchar(100),
    default_currency                char(3)       not null default 'USD',
    tax_registration_no             varchar(100),
    bank_details                    jsonb,
    credit_limit_amount             bigint        not null default 0,
    credit_limit_currency           char(3)       not null default 'USD',
    status                          varchar(10)   not null default 'Active',
    block_reason                    varchar(500),
    abn                             varchar(11),
    location_id                     char(26),                       -- loose cross-slice ref
    opening_balance_amount          bigint        not null default 0,
    opening_balance_currency        char(3)       not null default 'USD',
    opening_balance_side            varchar(6)    not null default 'CREDIT',
    opening_balance_date            date,
    opening_balance_exchange_rate   numeric(18,6),
    opening_balance_account_id      char(26),                       -- loose cross-slice ref

    created_at                      timestamptz   not null default now(),
    created_by                      char(26),
    updated_at                      timestamptz   not null default now(),
    updated_by                      char(26),
    deleted_at                      timestamptz,
    version                         bigint        not null default 0,

    constraint ck_suppliers_type    check (type in ('GOODS','SERVICES','BOTH')),
    constraint ck_suppliers_status  check (status in ('Active','Inactive','Blocked')),
    constraint ck_suppliers_ob_side check (opening_balance_side in ('DEBIT','CREDIT'))
);

-- Filter/sort covering index for the list endpoint (status + type + code order).
create index ix_suppliers_status on suppliers (status);
create index ix_suppliers_location_id on suppliers (location_id);

-- ---------------------------------------------------------------------
-- ENT-026a SupplierAttachment — supporting documents per supplier
-- ---------------------------------------------------------------------
create table supplier_attachments (
    id            bigint        generated by default as identity primary key,
    public_id     char(26)      not null unique,

    -- Same-slice link to the owning supplier's public_id (real FK, cascade).
    supplier_id   char(26)      not null
        references suppliers (public_id) on delete cascade,
    file_name     varchar(255)  not null,
    file_size     bigint        not null,
    mime_type     varchar(100)  not null,
    storage_key   varchar(500)  not null,
    uploaded_by   char(26),                                          -- loose ref to users

    created_at    timestamptz   not null default now(),
    created_by    char(26),
    updated_at    timestamptz   not null default now(),
    updated_by    char(26),
    deleted_at    timestamptz,
    version       bigint        not null default 0
);

create index ix_supplier_attachments_supplier_id
    on supplier_attachments (supplier_id);

-- =====================================================================
-- Permissions for the procurement "suppliers" slice
-- (procurement.<concept>.read/.write), granted to the admin role so the
-- @PreAuthorize checks are reachable. Fresh PERM8x ULIDs (exactly 26 chars)
-- — collision-free vs the existing seeded PERM01..PERM75 / ROLE01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA00000000000000PERM80', 'procurement.supplier.read',    'View suppliers',          'procurement', 'List, filter, and view suppliers and their attachments'),
  ('01J0AA00000000000000PERM81', 'procurement.supplier.write',   'Manage suppliers',        'procurement', 'Create, update, change status, and delete suppliers; manage attachments'),
  ('01J0AA00000000000000PERM82', 'procurement.attachment.read',  'View supplier documents', 'procurement', 'List and view supplier supporting documents'),
  ('01J0AA00000000000000PERM83', 'procurement.attachment.write', 'Manage supplier documents','procurement', 'Register and delete supplier supporting documents');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.supplier.read', 'procurement.supplier.write',
    'procurement.attachment.read', 'procurement.attachment.write')
where r.code = 'admin';
