-- =====================================================================
-- V41 — PROCUREMENT module, "orders" sub-slice.
--
-- Matches the JPA entities under
-- com.guru.erp.modules.procurement.orders.domain extending BaseEntity:
--   ENT-027  PurchaseRequisition       (header + approval workflow)
--   ENT-027a PurchaseRequisitionLine   (requisition lines)
--   ENT-028  PurchaseOrder             (header + status workflow)
--   ENT-028a PurchaseOrderLine         (order lines)
--   ENT-028b PurchaseOrderVersion      (FR-092 amendment history)
--
-- Money is bigint minor units + char(3) currency (never float); quantities
-- are numeric(18,6) fixed precision matching the reference + stock ledger.
-- Statuses persist as the human wire label ("Draft", "Under Review", …) via
-- AttributeConverters, guarded by check constraints below.
--
-- Cross-slice references (location, supplier, requester/buyer user, product,
-- variant, uom, tax code, source PR) are held as loose ULID char(26) columns
-- — no hard cross-slice FK, per the vertical-slice rule. Same-slice parent
-- links (line → header, version → PO) are real FKs. All reference
-- unique/check constraints and indexes are reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-027 PurchaseRequisition — US-017 / FR-080–086
-- ---------------------------------------------------------------------
create table purchase_requisitions (
    id                     bigint        generated by default as identity primary key,
    public_id              char(26)      not null unique,

    number                 varchar(30)   not null unique,
    location_id            char(26),                          -- loose cross-slice ref
    requester_user_id      char(26),                          -- loose cross-slice ref
    supplier_id            char(26),                          -- loose cross-slice ref (header supplier)
    currency               char(3),
    needed_by_date         timestamptz,
    status                 varchar(15)   not null default 'Draft',
    assigned_buyer_id      char(26),                          -- loose cross-slice ref
    rejection_reason       varchar(500),
    request_date           timestamptz,
    payment_terms          varchar(100),
    exchange_rate          numeric(12,6),
    invoice_discount_type  varchar(10),
    invoice_discount_value numeric(12,4) not null default 0,
    total_amount           bigint        not null default 0,
    notes                  text,

    created_at             timestamptz   not null default now(),
    created_by             char(26),
    updated_at             timestamptz   not null default now(),
    updated_by             char(26),
    deleted_at             timestamptz,
    version                bigint        not null default 0,

    constraint ck_purchase_requisitions_status
        check (status in ('Draft','Submitted','Under Review','Sent to Supplier','Converted','Rejected'))
);

create index ix_purchase_requisitions_location on purchase_requisitions (location_id);
create index ix_purchase_requisitions_supplier on purchase_requisitions (supplier_id);
create index ix_purchase_requisitions_status   on purchase_requisitions (status);

-- ---------------------------------------------------------------------
-- ENT-027a PurchaseRequisitionLine
-- ---------------------------------------------------------------------
create table purchase_requisition_lines (
    id                    bigint        generated by default as identity primary key,
    public_id             char(26)      not null unique,

    pr_id                 bigint        not null references purchase_requisitions (id) on delete cascade,
    line_no               integer       not null,
    product_id            char(26),                           -- loose cross-slice ref
    variant_id            char(26),                           -- loose cross-slice ref
    qty                   numeric(18,6) not null default 1,
    uom_id                char(26),                           -- loose cross-slice ref
    preferred_supplier_id char(26),                           -- loose cross-slice ref
    description           varchar(500),
    unit_price_amount     bigint        not null default 0,
    unit_price_currency   char(3)       not null default 'USD',
    discount_percent      numeric(5,2)  not null default 0,
    tax_code_id           char(26),                           -- loose cross-slice ref
    line_total_amount     bigint        not null default 0,
    status                varchar(12)   not null default 'Open',

    created_at            timestamptz   not null default now(),
    created_by            char(26),
    updated_at            timestamptz   not null default now(),
    updated_by            char(26),
    deleted_at            timestamptz,
    version               bigint        not null default 0,

    constraint uq_pr_lines_pr_line unique (pr_id, line_no),
    constraint ck_pr_lines_qty_positive check (qty > 0),
    constraint ck_pr_lines_status check (status in ('Open','Converted','Rejected'))
);

create index ix_pr_lines_pr      on purchase_requisition_lines (pr_id);
create index ix_pr_lines_product on purchase_requisition_lines (product_id);

-- ---------------------------------------------------------------------
-- ENT-028 PurchaseOrder — US-018 / FR-087–093
-- ---------------------------------------------------------------------
create table purchase_orders (
    id                     bigint        generated by default as identity primary key,
    public_id              char(26)      not null unique,

    number                 varchar(30)   not null unique,
    supplier_id            char(26)      not null,             -- loose cross-slice ref
    location_id            char(26),                           -- loose cross-slice ref
    po_date                timestamptz   not null default now(),
    expected_delivery_date timestamptz,
    currency               char(3)       not null default 'USD',
    exchange_rate          numeric(18,8) not null default 1,
    payment_terms          varchar(100),
    source_pr_id           char(26),                           -- loose cross-slice ref (originating PR)
    status                 varchar(20)   not null default 'Draft',
    close_reason           varchar(500),
    po_version             integer       not null default 1,
    invoice_discount_type  varchar(10),
    invoice_discount_value numeric(12,4) not null default 0,
    is_direct              boolean       not null default false,
    notes                  text,

    created_at             timestamptz   not null default now(),
    created_by             char(26),
    updated_at             timestamptz   not null default now(),
    updated_by             char(26),
    deleted_at             timestamptz,
    version                bigint        not null default 0,

    constraint ck_purchase_orders_status
        check (status in ('Draft','Submitted','Approved','Sent','Partially Received',
                          'Received','Closed','Cancelled'))
);

create index ix_purchase_orders_created_at on purchase_orders (created_at);
create index ix_purchase_orders_supplier   on purchase_orders (supplier_id);
create index ix_purchase_orders_location   on purchase_orders (location_id);
create index ix_purchase_orders_source_pr  on purchase_orders (source_pr_id);

-- ---------------------------------------------------------------------
-- ENT-028a PurchaseOrderLine
-- ---------------------------------------------------------------------
create table purchase_order_lines (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    po_id               bigint        not null references purchase_orders (id) on delete cascade,
    line_no             integer       not null,
    product_id          char(26),                             -- loose cross-slice ref
    qty_ordered         numeric(18,6) not null,
    qty_received_total  numeric(18,6) not null default 0,
    uom_id              char(26),                             -- loose cross-slice ref
    unit_price_amount   bigint        not null default 0,
    unit_price_currency char(3)       not null default 'USD',
    discount_percent    numeric(5,2)  not null default 0,
    tax_code_id         char(26),                             -- loose cross-slice ref
    tax_rate_percent    numeric(10,4),
    variant_id          char(26),                             -- loose cross-slice ref
    variant_name        varchar(500),
    line_total_amount   bigint        not null default 0,
    line_total_currency char(3)       not null default 'USD',

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_po_lines_po_line unique (po_id, line_no),
    constraint ck_po_lines_qty_positive check (qty_ordered > 0),
    constraint ck_po_lines_discount check (discount_percent >= 0 and discount_percent <= 100)
);

create index ix_po_lines_po      on purchase_order_lines (po_id);
create index ix_po_lines_product on purchase_order_lines (product_id);

-- ---------------------------------------------------------------------
-- ENT-028b PurchaseOrderVersion — FR-092 amendment history
-- ---------------------------------------------------------------------
create table purchase_order_versions (
    id          bigint      generated by default as identity primary key,
    public_id   char(26)    not null unique,

    po_id       bigint      not null references purchase_orders (id) on delete cascade,
    version_no  integer     not null,
    snapshot    jsonb       not null default '{}'::jsonb,
    reason      varchar(500),

    created_at  timestamptz not null default now(),
    created_by  char(26),
    updated_at  timestamptz not null default now(),
    updated_by  char(26),
    deleted_at  timestamptz,
    version     bigint      not null default 0
);

create index ix_po_versions_po on purchase_order_versions (po_id);

-- =====================================================================
-- Permissions for the procurement "orders" slice
-- (procurement.<concept>.read/.write), granted to the admin role so the
-- @PreAuthorize checks are reachable. Fresh PERM8x ULIDs (exactly 26 chars)
-- — collision-free vs the existing seeded PERM01..PERM75 / PERM80..PERM83
-- (V40 suppliers) / ROLE01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA00000000000000PERM85', 'procurement.requisition.read',  'View purchase requisitions',   'procurement', 'List, filter, and view purchase requisitions and their lines'),
  ('01J0AA00000000000000PERM86', 'procurement.requisition.write', 'Manage purchase requisitions', 'procurement', 'Create, edit, submit, transition (approve/reject), and delete purchase requisitions'),
  ('01J0AA00000000000000PERM87', 'procurement.order.read',        'View purchase orders',         'procurement', 'List, filter, view purchase orders and their amendment version history'),
  ('01J0AA00000000000000PERM88', 'procurement.order.write',       'Manage purchase orders',       'procurement', 'Create, amend, transition (submit/approve/send/receive/close/cancel), delete, and convert requisitions to purchase orders');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.requisition.read', 'procurement.requisition.write',
    'procurement.order.read', 'procurement.order.write')
where r.code = 'admin';
