-- =====================================================================
-- V42 — PROCUREMENT module, "receipts" sub-slice (US-018 / FR-094–097).
--
-- Goods receipts against Purchase Orders: GoodsReceipt + lines. Confirming
-- a receipt ("receive") posts stock movements via an outbox event
-- (procurement.goods_receipt.received) consumed by the inventory stock slice
-- — no ledger table is written here and no cross-slice class is hard-called.
-- Status workflow Draft → Approved → Partially Received → Received, guarded
-- by a check constraint; the status column stores the human wire label
-- ('Draft', 'Approved', …) via the entity AttributeConverter.
--
-- Matches the JPA entities under
-- com.guru.erp.modules.procurement.receipts.domain extending BaseEntity.
--
-- Cross-slice references (purchase order, purchase order line, location,
-- variant, receiver user) are held as loose ULID char(26) columns — no hard
-- cross-slice FK (app-layer resolution per the vertical-slice rule).
-- Same-slice references (line → header) are real FKs. Constraints, the unique
-- receipt number, and the covering indexes are reproduced from the reference
-- model (app/procurement/models.py GoodsReceipt / GoodsReceiptLine).
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-029 GoodsReceipt
-- ---------------------------------------------------------------------
create table goods_receipts (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    number              varchar(30)  not null,
    po_id               char(26)     not null,            -- loose cross-slice ref (purchase order)
    location_id         char(26)     not null,            -- loose cross-slice ref
    received_at         timestamptz  not null default now(),
    received_by         char(26),                          -- loose cross-slice ref (user)
    status              varchar(20)  not null default 'Draft',
    auto_receipt        boolean      not null default false,
    delivery_note_no    varchar(100),
    notes               text,

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_goods_receipts_number unique (number),
    constraint ck_goods_receipts_status
        check (status in ('Draft','Approved','Partially Received','Received','Confirmed'))
);

-- Reference: Index("ix_goods_receipts_received_at", "received_at").
create index ix_goods_receipts_received_at on goods_receipts (received_at);
-- Common filter: receipts for a given PO.
create index ix_goods_receipts_po on goods_receipts (po_id);

-- ---------------------------------------------------------------------
-- ENT-029a GoodsReceiptLine
-- ---------------------------------------------------------------------
create table goods_receipt_lines (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    grn_id              bigint        not null references goods_receipts (id) on delete cascade,
    po_line_id          char(26),                          -- loose cross-slice ref (PO line); null = standalone
    variant_id          char(26),                          -- loose cross-slice ref
    qty_received        numeric(18,6) not null,
    qty_discrepancy     numeric(18,6) not null default 0,
    discrepancy_type    varchar(15),
    discrepancy_note    varchar(500),
    batch_no            varchar(100),
    serial_no           varchar(100),
    expiry_date         timestamptz,
    supplier_barcode    varchar(64),
    manufacture_date    timestamptz,
    mrp_amount          bigint,
    mrp_currency        char(3),
    sell_price_amount   bigint,
    sell_price_currency char(3),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_grn_lines_qty_non_negative            check (qty_received >= 0),
    constraint ck_grn_lines_discrepancy_non_negative    check (qty_discrepancy >= 0),
    constraint ck_grn_lines_discrepancy_type
        check (discrepancy_type is null or discrepancy_type in ('Short','Damaged','Wrong Item'))
);

-- Reference: Index("ix_goods_receipt_lines_po_line_id", "po_line_id").
create index ix_goods_receipt_lines_po_line_id on goods_receipt_lines (po_line_id);
create index ix_goods_receipt_lines_grn on goods_receipt_lines (grn_id);
create index ix_goods_receipt_lines_variant on goods_receipt_lines (variant_id);

-- =====================================================================
-- Permissions for the procurement "receipt" slice
-- (procurement.<concept>.read/.write), granted to the admin role so the
-- @PreAuthorize checks are reachable. Fresh PERM9x ULIDs — collision-free
-- vs the seeded PERM01..PERM75 / ROLE01 set from prior modules.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM91', 'procurement.receipt.read',  'View goods receipts',   'procurement', 'List and view goods receipts (GRNs) against purchase orders'),
  ('01J0AA000000000000PERM92', 'procurement.receipt.write', 'Manage goods receipts', 'procurement', 'Create, update, delete, transition, and confirm (receive) goods receipts');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.receipt.read', 'procurement.receipt.write')
where r.code = 'admin';
