-- =====================================================================
-- V43 — PROCUREMENT module, "bills" sub-slice.
--
-- Matches the JPA entities under
-- com.springboot.erp.modules.procurement.bills.domain extending BaseEntity:
--   ENT-030  SupplierBill              (AP invoice header)
--   ENT-030a SupplierBillLine          (bill lines; 3-way match anchor)
--   ENT-030b SupplierBillGrnLink       (bill ↔ GRN link)
--   ENT-030c SupplierBillPoLink        (bill ↔ PO link)
--   ENT-033  SupplierPayment           (money paid TO a supplier)
--   ENT-033a SupplierPaymentTender     (split-payment method line)
--   ENT-034  AmountReceived            (refund / credit-note receipt)
--
-- Money is bigint minor units + char(3) currency (never float);
-- quantities are numeric(18,6). Bill posting emits a GL event via the
-- OutboxPublisher — no GL tables are written here.
--
-- Cross-slice references (supplier, PO, GRN, PO line, GRN line, product,
-- variant, tax code, purchase return, payment method) are held as loose
-- ULID char(26) columns — no hard cross-slice FK, per the vertical-slice
-- rule. Same-slice parent↔child FKs are real. All reference unique / check
-- constraints + indexes are reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-030 SupplierBill (FR-098–101)
-- ---------------------------------------------------------------------
create table supplier_bills (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    number              varchar(30)   not null unique,
    supplier_id         char(26)      not null,            -- loose cross-slice ref
    po_id               char(26),                          -- loose cross-slice ref (primary PO)
    supplier_bill_no    varchar(100),
    bill_date           timestamptz   not null,
    due_date            timestamptz,
    currency            char(3)       not null default 'USD',
    exchange_rate       numeric(18,8) not null default 1.0,
    subtotal_amount     bigint        not null default 0,
    tax_amount          bigint        not null default 0,
    total_amount        bigint        not null default 0,
    status              varchar(25)   not null default 'Draft',
    match_status        varchar(20),
    notes               text,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_supplier_bills_status
        check (status in ('Draft','Received','Approved','Paid','Partially Received',
                          'Cancelled','Invoiced Not Received'))
);

create index ix_supplier_bills_supplier_id on supplier_bills (supplier_id);
create index ix_supplier_bills_po_id        on supplier_bills (po_id);
create index ix_supplier_bills_created_at   on supplier_bills (created_at);

-- ---------------------------------------------------------------------
-- ENT-030a SupplierBillLine
-- ---------------------------------------------------------------------
create table supplier_bill_lines (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    bill_id             bigint        not null references supplier_bills (id) on delete cascade,
    po_line_id          char(26),                          -- loose cross-slice ref
    grn_line_id         char(26),                          -- loose cross-slice ref
    product_id          char(26),                          -- loose cross-slice ref
    variant_id          char(26),                          -- loose cross-slice ref
    description         varchar(500),
    qty                 numeric(18,6) not null default 1,
    unit_price_amount   bigint        not null default 0,
    tax_code_id         char(26),                          -- loose cross-slice ref
    line_total_amount   bigint        not null default 0,
    match_status        varchar(20),
    is_capital_item     boolean       not null default false,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_supplier_bill_lines_qty_positive check (qty > 0)
);

create index ix_supplier_bill_lines_bill_id     on supplier_bill_lines (bill_id);
create index ix_supplier_bill_lines_po_line_id  on supplier_bill_lines (po_line_id);
create index ix_supplier_bill_lines_grn_line_id on supplier_bill_lines (grn_line_id);

-- ---------------------------------------------------------------------
-- ENT-030b SupplierBillGrnLink — many-to-many bill ↔ GRN
-- ---------------------------------------------------------------------
create table supplier_bill_grn_links (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    bill_id             bigint        not null references supplier_bills (id) on delete cascade,
    grn_id              char(26)      not null,            -- loose cross-slice ref

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_bill_grn_links unique (bill_id, grn_id)
);

create index ix_supplier_bill_grn_links_bill_id on supplier_bill_grn_links (bill_id);
create index ix_supplier_bill_grn_links_grn_id  on supplier_bill_grn_links (grn_id);

-- ---------------------------------------------------------------------
-- ENT-030c SupplierBillPoLink — many-to-many bill ↔ PO
-- ---------------------------------------------------------------------
create table supplier_bill_po_links (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    bill_id             bigint        not null references supplier_bills (id) on delete cascade,
    po_id               char(26)      not null,            -- loose cross-slice ref

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_bill_po_links unique (bill_id, po_id)
);

create index ix_supplier_bill_po_links_bill_id on supplier_bill_po_links (bill_id);
create index ix_supplier_bill_po_links_po_id   on supplier_bill_po_links (po_id);

-- ---------------------------------------------------------------------
-- ENT-033 SupplierPayment
-- ---------------------------------------------------------------------
create table supplier_payments (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    number              varchar(30)   not null unique,
    supplier_id         char(26)      not null,            -- loose cross-slice ref
    po_id               char(26),                          -- loose cross-slice ref
    invoice_reference   varchar(100),
    payment_method_id   char(26)      not null,            -- loose cross-slice ref
    payment_method_name varchar(100)  not null,
    payment_date        timestamptz   not null,
    amount_amount       bigint        not null,
    amount_currency     char(3)       not null,
    exchange_rate       numeric(18,8) not null default 1.0,
    base_amount         bigint        not null default 0,
    reference_no        varchar(100),
    notes               text,
    discount_type       varchar(10),
    discount_value      bigint        not null default 0,
    status              varchar(20)   not null default 'Draft',
    status_history      jsonb         not null default '[]'::jsonb,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_supplier_payments_amount_positive check (amount_amount > 0),
    constraint ck_supplier_payments_discount_type
        check (discount_type is null or discount_type in ('percent','amount')),
    constraint ck_supplier_payments_status
        check (status in ('Draft','Approved','Partially Paid','Paid'))
);

create index ix_supplier_payments_supplier_id  on supplier_payments (supplier_id);
create index ix_supplier_payments_po_id        on supplier_payments (po_id);
create index ix_supplier_payments_status       on supplier_payments (status);
create index ix_supplier_payments_payment_date on supplier_payments (payment_date);

-- ---------------------------------------------------------------------
-- ENT-033a SupplierPaymentTender — split-payment method line
-- ---------------------------------------------------------------------
create table supplier_payment_tenders (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    payment_id          bigint        not null references supplier_payments (id) on delete cascade,
    payment_method_id   char(26)      not null,            -- loose cross-slice ref
    payment_method_name varchar(100)  not null,
    amount_amount       bigint        not null,
    amount_currency     char(3)       not null,
    reference_no        varchar(100),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_supplier_payment_tenders_amount_positive check (amount_amount > 0)
);

create index ix_supplier_payment_tenders_payment on supplier_payment_tenders (payment_id);

-- ---------------------------------------------------------------------
-- ENT-034 AmountReceived — refund / credit-note receipt
-- ---------------------------------------------------------------------
create table amount_received (
    id                    bigint        generated by default as identity primary key,
    public_id             char(26)      not null unique,

    number                varchar(30)   not null unique,
    supplier_id           char(26)      not null,          -- loose cross-slice ref
    purchase_return_id    char(26),                        -- loose cross-slice ref
    po_id                 char(26),                        -- loose cross-slice ref
    credit_note_reference varchar(100),
    payment_method_id     char(26)      not null,          -- loose cross-slice ref
    payment_method_name   varchar(100)  not null,
    received_date         timestamptz   not null,
    amount_amount         bigint        not null,
    amount_currency       char(3)       not null,
    exchange_rate         numeric(18,8) not null default 1.0,
    base_amount           bigint        not null default 0,
    reference_no          varchar(100),
    notes                 text,
    discount_type         varchar(10),
    discount_value        bigint        not null default 0,
    status                varchar(20)   not null default 'Draft',
    status_history        jsonb         not null default '[]'::jsonb,

    created_at            timestamptz   not null default now(),
    created_by            char(26),
    updated_at            timestamptz   not null default now(),
    updated_by            char(26),
    deleted_at            timestamptz,
    version               bigint        not null default 0,

    constraint ck_amount_received_amount_positive check (amount_amount > 0),
    constraint ck_amount_received_discount_type
        check (discount_type is null or discount_type in ('percent','amount')),
    constraint ck_amount_received_status
        check (status in ('Draft','Approved','Confirmed','Voided'))
);

create index ix_amount_received_supplier_id   on amount_received (supplier_id);
create index ix_amount_received_po_id          on amount_received (po_id);
create index ix_amount_received_status         on amount_received (status);
create index ix_amount_received_received_date  on amount_received (received_date);

-- =====================================================================
-- Permissions for the procurement "bills" slice (procurement.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM9x ULIDs — collision-free vs the seeded PERM01..PERM75 / ROLE01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA000000000000PERM95', 'procurement.bill.read',             'View supplier bills',     'procurement', 'List, view, and filter supplier bills (AP invoices)'),
  ('01J0AA000000000000PERM96', 'procurement.bill.write',            'Manage supplier bills',   'procurement', 'Create, edit, approve, and delete supplier bills'),
  ('01J0AA000000000000PERM97', 'procurement.payment.read',          'View supplier payments',  'procurement', 'List, view, and filter supplier payments'),
  ('01J0AA000000000000PERM98', 'procurement.payment.write',         'Manage supplier payments','procurement', 'Create, edit, transition, and delete supplier payments'),
  ('01J0AA000000000000PERM99', 'procurement.amount_received.read',  'View amount received',    'procurement', 'List, view, and filter refund / credit-note receipts'),
  ('01J0AA000000000000PERM9A', 'procurement.amount_received.write', 'Manage amount received',  'procurement', 'Create, edit, transition, and delete refund / credit-note receipts');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.bill.read', 'procurement.bill.write',
    'procurement.payment.read', 'procurement.payment.write',
    'procurement.amount_received.read', 'procurement.amount_received.write')
where r.code = 'admin';
