-- =====================================================================
-- V44 — PROCUREMENT module, "returns" sub-slice (supplier returns / debit
-- notes raised against a goods receipt).
--
-- Matches the JPA entities under
-- com.springboot.erp.modules.procurement.returns.domain extending BaseEntity:
--   ENT-031  SupplierReturn      (header — supplier + GRN, debit note, FX)
--   ENT-031a SupplierReturnLine  (returned lines against GRN lines)
--
-- Status workflow: Draft -> Confirmed (persisted as the human label to
-- satisfy the ck_supplier_returns_status check). On Confirmed the stock
-- relief + V-007 debit-note GL posting are performed by the inventory /
-- finance modules, driven by outbox events this slice publishes.
--
-- Cross-slice references (supplier, GRN, GRN line, variant) are held as
-- loose ULID char(26) columns — no hard cross-slice FK, per the
-- vertical-slice rule. Money is bigint minor units + char(3) currency;
-- quantities are numeric(18,6) fixed precision (never float). Reference
-- unique/check constraints and indexes are reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-031 SupplierReturn — US-020 / FR-109-113
-- ---------------------------------------------------------------------
create table supplier_returns (
    id                        bigint        generated by default as identity primary key,
    public_id                 char(26)      not null unique,

    number                    varchar(30)   not null unique,
    supplier_id               char(26)      not null,            -- loose cross-slice ref
    grn_id                    char(26)      not null,            -- loose cross-slice ref
    returned_at               timestamptz   not null,
    status                    varchar(12)   not null default 'Draft',

    debit_note_amount         bigint        not null default 0,
    debit_note_currency       char(3)       not null default 'USD',
    -- FX trail — resolved at creation against the GRN's company + returned_at.
    -- rate=1 and base == txn when the debit-note currency is the base currency.
    exchange_rate             numeric(18,8) not null default 1,
    base_debit_note_amount    bigint        not null default 0,
    base_debit_note_currency  char(3)       not null default 'USD',

    created_at                timestamptz   not null default now(),
    created_by                char(26),
    updated_at                timestamptz   not null default now(),
    updated_by                char(26),
    deleted_at                timestamptz,
    version                   bigint        not null default 0,

    constraint ck_supplier_returns_status
        check (status in ('Draft','Confirmed'))
);

-- Reference: Index("ix_supplier_returns_returned_at", "returned_at").
create index ix_supplier_returns_returned_at
    on supplier_returns (returned_at);
-- Supports the list filter by supplier / GRN.
create index ix_supplier_returns_supplier_id on supplier_returns (supplier_id);
create index ix_supplier_returns_grn_id      on supplier_returns (grn_id);

-- ---------------------------------------------------------------------
-- ENT-031a SupplierReturnLine
-- ---------------------------------------------------------------------
create table supplier_return_lines (
    id            bigint        generated by default as identity primary key,
    public_id     char(26)      not null unique,

    return_id     bigint        not null references supplier_returns (id) on delete cascade,
    grn_line_id   char(26),                                       -- loose cross-slice ref
    variant_id    char(26),                                       -- loose cross-slice ref
    qty           numeric(18,6) not null,
    reason        varchar(500),

    created_at    timestamptz   not null default now(),
    created_by    char(26),
    updated_at    timestamptz   not null default now(),
    updated_by    char(26),
    deleted_at    timestamptz,
    version       bigint        not null default 0,

    -- Reference: CheckConstraint("qty > 0", name="ck_return_lines_qty_positive").
    constraint ck_supplier_return_lines_qty_positive check (qty > 0)
);

-- Reference: return_id is indexed (ForeignKey index=True); plus grn_line_id
-- for the "already returned against this GRN line" running-total query.
create index ix_supplier_return_lines_return_id   on supplier_return_lines (return_id);
create index ix_supplier_return_lines_grn_line_id on supplier_return_lines (grn_line_id);

-- =====================================================================
-- Permissions for the procurement "returns" slice
-- (procurement.<concept>.read/.write), granted to the admin role so the
-- @PreAuthorize checks are reachable. Fresh PERM10x ULIDs — collision-free
-- vs the existing seeded PERM01..PERM75 / ROLE01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM100', 'procurement.return.read',  'View supplier returns',   'procurement', 'List, filter, and view supplier returns (debit notes) raised against goods receipts'),
  ('01J0AA0000000000000PERM101', 'procurement.return.write', 'Manage supplier returns', 'procurement', 'Create, edit, confirm, and delete supplier returns');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.return.read', 'procurement.return.write')
where r.code = 'admin';
