-- =====================================================================
-- V45 — PROCUREMENT module, "landed" sub-slice (US-019 + barcode setup).
--
-- Landed costs: LandedCost + LandedCostAllocation (allocate freight/duty
-- across PO/GRN lines with money math + allocation methods), plus the
-- many-to-many bridges LandedCostGrnLink / LandedCostPoLink. Applying a
-- landed cost revalues stock — emitted as an outbox event, never a hard
-- cross-module call.
--
-- Unit barcodes: UnitBarcode + UnitBarcodeItem (per-unit / bundle barcode
-- assignment at GRN time) and LabelSize (seeded print-label stock sizes).
--
-- Matches the JPA entities under
-- com.springboot.erp.modules.procurement.landed.domain extending BaseEntity.
--
-- Cross-slice references (GRN, GRN line, PO, PO line, supplier, product,
-- variant, location) are held as loose ULID char(26) columns — no hard
-- cross-slice FK (app-layer resolution per the vertical-slice rule).
-- Same-slice references (allocation → landed cost, item → unit barcode)
-- are real FKs. Money is bigint minor units + char(3) currency; quantities
-- are numeric(18,6). Charge type / allocation basis / status enums persist
-- UPPERCASE (@Enumerated STRING); unit-barcode status persists lowercase
-- via an AttributeConverter, guarded by check constraints below.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-032 LandedCost
-- ---------------------------------------------------------------------
create table landed_costs (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    grn_id              char(26),                            -- loose cross-slice ref (primary GRN)
    po_id               char(26),                            -- loose cross-slice ref (primary PO)
    invoice_number      varchar(30),
    charge_type         varchar(30)   not null,
    supplier_id         char(26),                            -- loose cross-slice ref
    amount              bigint        not null,
    currency            char(3)       not null default 'USD',
    exchange_rate       numeric(18,8) not null default 1,
    base_amount         bigint        not null default 0,
    base_currency       char(3)       not null default 'USD',
    allocation_basis    varchar(10)   not null,
    status              varchar(10)   not null default 'DRAFT',
    allocated_at        timestamptz   not null default now(),
    applied_at          timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_landed_costs_amount_positive check (amount > 0),
    constraint ck_landed_costs_charge_type
        check (charge_type in ('FREIGHT','DUTY','CUSTOMS_CLEARANCE','INSURANCE','HANDLING',
                               'BROKERAGE','DOCUMENTATION','DEMURRAGE','STORAGE','INSPECTION','OTHER')),
    constraint ck_landed_costs_allocation_basis
        check (allocation_basis in ('VALUE','QUANTITY','WEIGHT','VOLUME','EQUAL')),
    constraint ck_landed_costs_status
        check (status in ('DRAFT','APPLIED','REVERSED'))
);

create index ix_landed_costs_grn_id on landed_costs (grn_id);
create index ix_landed_costs_po_id on landed_costs (po_id);
create index ix_landed_costs_invoice_number on landed_costs (invoice_number);
create index ix_landed_costs_supplier_id on landed_costs (supplier_id);

-- ---------------------------------------------------------------------
-- ENT-032a LandedCostAllocation
-- ---------------------------------------------------------------------
create table landed_cost_allocations (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    landed_cost_id      bigint        not null references landed_costs (id) on delete cascade,
    grn_line_id         char(26),                            -- loose cross-slice ref
    po_line_id          char(26),                            -- loose cross-slice ref
    allocated_amount    bigint        not null,
    allocated_currency  char(3)       not null default 'USD',
    alloc_qty           numeric(18,6),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0
);

create index ix_landed_cost_allocations_landed_cost on landed_cost_allocations (landed_cost_id);
create index ix_landed_cost_allocations_grn_line on landed_cost_allocations (grn_line_id);
create index ix_landed_cost_allocations_po_line on landed_cost_allocations (po_line_id);

-- ---------------------------------------------------------------------
-- ENT-032b LandedCostGrnLink — M:N landed cost ↔ GRN
-- ---------------------------------------------------------------------
create table landed_cost_grn_links (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    landed_cost_id      char(26)     not null,               -- ULID of owning landed cost
    grn_id              char(26)     not null,               -- loose cross-slice ref

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_landed_cost_grn_links unique (landed_cost_id, grn_id)
);

create index ix_landed_cost_grn_links_grn on landed_cost_grn_links (grn_id);

-- ---------------------------------------------------------------------
-- ENT-032c LandedCostPoLink — M:N landed cost ↔ PurchaseOrder
-- ---------------------------------------------------------------------
create table landed_cost_po_links (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    landed_cost_id      char(26)     not null,               -- ULID of owning landed cost
    po_id               char(26)     not null,               -- loose cross-slice ref

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_landed_cost_po_links unique (landed_cost_id, po_id)
);

create index ix_landed_cost_po_links_po on landed_cost_po_links (po_id);

-- ---------------------------------------------------------------------
-- UnitBarcode — per-unit barcode assigned at GRN time
-- ---------------------------------------------------------------------
create table unit_barcodes (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    grn_line_id         char(26),                            -- loose cross-slice ref
    grn_id              char(26),                            -- loose cross-slice ref
    location_id         char(26),                            -- loose cross-slice ref
    barcode             varchar(100)  not null,
    barcode_format      varchar(16)   not null default 'EAN13',
    is_bundle           boolean       not null default false,
    product_id          char(26),                            -- loose cross-slice ref (null when bundle)
    variant_id          char(26),                            -- loose cross-slice ref
    qty                 numeric(18,6) not null default 1,
    mrp_amount          bigint,
    mrp_currency        char(3),
    sell_price_amount   bigint,
    sell_price_currency char(3),
    batch_no            varchar(100),
    serial_no           varchar(100),
    expiry_date         date,
    entry_date          date,
    status              varchar(16)   not null default 'available',
    notes               varchar(500),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_unit_barcodes_barcode unique (barcode),
    constraint ck_unit_barcodes_format
        check (barcode_format in ('EAN13','UPCA','CODE128','OTHER')),
    constraint ck_unit_barcodes_status
        check (status in ('available','sold','returned','damaged','reserved')),
    constraint ck_unit_barcodes_qty_positive check (qty > 0)
);

create index ix_unit_barcodes_grn_line_id on unit_barcodes (grn_line_id);
create index ix_unit_barcodes_grn_id on unit_barcodes (grn_id);
create index ix_unit_barcodes_product_id on unit_barcodes (product_id);
create index ix_unit_barcodes_variant_id on unit_barcodes (variant_id);
create index ix_unit_barcodes_status on unit_barcodes (status);

-- ---------------------------------------------------------------------
-- UnitBarcodeItem — bundle-component rows (is_bundle = true)
-- ---------------------------------------------------------------------
create table unit_barcode_items (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)      not null unique,

    unit_barcode_id     bigint        not null references unit_barcodes (id) on delete cascade,
    grn_line_id         char(26),                            -- loose cross-slice ref
    product_id          char(26)      not null,              -- loose cross-slice ref
    variant_id          char(26),                            -- loose cross-slice ref
    qty                 numeric(18,6) not null default 1,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_unit_barcode_items_qty_positive check (qty > 0)
);

create index ix_unit_barcode_items_unit_barcode on unit_barcode_items (unit_barcode_id);

-- ---------------------------------------------------------------------
-- LabelSize — seeded print-label stock sizes (served read-only)
-- ---------------------------------------------------------------------
create table label_sizes (
    id                  bigint generated by default as identity primary key,
    public_id           char(26)     not null unique,

    name                varchar(50)  not null,
    width_mm            integer      not null,
    height_mm           integer      not null,
    is_default          boolean      not null default false,
    sort_order          integer      not null default 0,
    is_active           boolean      not null default true,

    created_at          timestamptz  not null default now(),
    created_by          char(26),
    updated_at          timestamptz  not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint       not null default 0,

    constraint uq_label_sizes_name unique (name)
);

-- Seed the common thermal-label stock sizes offered in the Print Label dialog.
insert into label_sizes (public_id, name, width_mm, height_mm, is_default, sort_order, is_active) values
  ('01J0AA00000000000LABELSZ01', '38 x 25 mm', 38, 25, true,  10, true),
  ('01J0AA00000000000LABELSZ02', '50 x 25 mm', 50, 25, false, 20, true),
  ('01J0AA00000000000LABELSZ03', '50 x 30 mm', 50, 30, false, 30, true),
  ('01J0AA00000000000LABELSZ04', '100 x 50 mm', 100, 50, false, 40, true),
  ('01J0AA00000000000LABELSZ05', '100 x 150 mm', 100, 150, false, 50, true);

-- =====================================================================
-- Permissions for the procurement "landed" slice (procurement.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM10x ULIDs — no collision with the seeded PERMxx / ROLE01 set
-- (existing run PERM01..PERM75 across prior modules).
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM104', 'procurement.landed_cost.read',  'View landed costs',    'procurement', 'List and view landed-cost invoices and their allocations'),
  ('01J0AA0000000000000PERM105', 'procurement.landed_cost.write', 'Manage landed costs',  'procurement', 'Record, edit, apply (revalue stock), and delete landed costs'),
  ('01J0AA0000000000000PERM106', 'procurement.unit_barcode.read', 'View unit barcodes',   'procurement', 'List, view, and check unit barcodes and bundles'),
  ('01J0AA0000000000000PERM107', 'procurement.unit_barcode.write','Manage unit barcodes', 'procurement', 'Assign, generate, edit, and delete unit barcodes and bundles'),
  ('01J0AA0000000000000PERM108', 'procurement.label_size.read',   'View label sizes',     'procurement', 'List the print-label stock sizes for the barcode label dialog');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'procurement.landed_cost.read', 'procurement.landed_cost.write',
    'procurement.unit_barcode.read', 'procurement.unit_barcode.write',
    'procurement.label_size.read')
where r.code = 'admin';
