-- =====================================================================
-- V50 — POS module, "registers" sub-slice (US-005.1 register/terminal setup
-- + US-037 till sessions).
--
-- Matches the JPA entities under com.springboot.erp.modules.pos.registers.domain
-- extending BaseEntity:
--   ENT-060  Register            (a POS lane/terminal at a STORE location)
--   ENT-060a RegisterPeripheral  (bound printer/scanner/drawer config)
--   PosTillSession               (a cashier's till shift: opening/closing float)
--   PosTillMovement              (append-only cash movement within a session)
--
-- Register -> Location is a cross-slice reference (settings.location) held as
-- a loose ULID char(26) column — no hard cross-slice FK, per the
-- vertical-slice rule. RegisterPeripheral IS same-slice (child of Register)
-- so it keeps a real FK + cascade delete. PosTillSession -> Register is also
-- same-slice (real FK, restrict — a register with till history cannot be
-- hard-deleted, reference RegisterHasHistoryError). PosTillMovement ->
-- PosTillSession is same-slice (real FK, cascade). Cross-module references
-- (cashier user, approving manager, the POS transaction that produced a
-- SALE/CHANGE/REFUND_OUT leg) are loose ULID char(26) columns.
--
-- Money is bigint minor units + char(3) currency (platform Money embeddable).
-- Register.status persists lower-case via RegisterStatusConverter (matches
-- reference RegisterStatus.value, e.g. "active"); operating_mode / peripheral
-- type / connection / till session status / till movement type persist
-- UPPERCASE via @Enumerated(STRING) (reference wire values already upper),
-- so those need no converter.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-060 Register — US-005.1 / FR-25.1 / FR-25.6 / FR-25.9
-- ---------------------------------------------------------------------
create table registers (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    location_id         char(26)      not null,               -- loose cross-slice ref (settings.location)
    code                varchar(20)   not null,
    display_name        varchar(100)  not null,
    operating_mode      varchar(20)   not null default 'FULL_SERVICE',
    status              varchar(16)   not null default 'active',

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_registers_location_code unique (location_id, code),
    constraint ck_registers_operating_mode
        check (operating_mode in ('FULL_SERVICE','EXPRESS','MANAGER_ONLY')),
    constraint ck_registers_status check (status in ('active','inactive'))
);

create index ix_registers_location_id on registers (location_id);

-- ---------------------------------------------------------------------
-- ENT-060a RegisterPeripheral — bound hardware per Register
-- ---------------------------------------------------------------------
create table register_peripherals (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    register_id         bigint        not null references registers (id) on delete cascade,
    type                varchar(20)   not null,
    connection          varchar(16)   not null,
    config              jsonb         not null default '{}'::jsonb,
    enabled             boolean       not null default true,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_register_peripherals_type unique (register_id, type),
    constraint ck_register_peripherals_type
        check (type in ('RECEIPT_PRINTER','CASH_DRAWER','SCANNER','CARD_READER','LABEL_PRINTER')),
    constraint ck_register_peripherals_connection
        check (connection in ('USB','NETWORK','BLUETOOTH','HID','SERIAL'))
);

create index ix_register_peripherals_register_id on register_peripherals (register_id);

-- ---------------------------------------------------------------------
-- PosTillSession — US-037 FR-191..194
-- ---------------------------------------------------------------------
create table pos_till_sessions (
    id                       bigint        generated by default as identity primary key,
    public_id                char(26)      not null unique,

    register_id             bigint        not null references registers (id) on delete restrict,
    location_id             char(26)      not null,            -- loose cross-slice ref, denormalised at open time
    cashier_id               char(26),                         -- loose cross-slice ref (access.user)
    status                  varchar(8)    not null default 'OPEN',
    opening_float_amount     bigint        not null default 0,
    opening_float_currency   char(3)       not null,
    expected_cash_amount     bigint,
    expected_cash_currency   char(3),
    counted_cash_amount      bigint,
    counted_cash_currency    char(3),
    variance_amount          bigint,
    variance_approved_by     char(26),                         -- loose cross-slice ref (access.user)
    variance_approved_at     timestamptz,
    opened_at                timestamptz   not null default now(),
    closed_at                 timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_pos_till_sessions_status check (status in ('OPEN','CLOSED'))
);

create index ix_pos_till_sessions_register_id on pos_till_sessions (register_id);

-- Reference uq_till_one_open_per_register — at most one OPEN session per register.
create unique index uq_till_one_open_per_register
    on pos_till_sessions (register_id)
    where status = 'OPEN';

-- ---------------------------------------------------------------------
-- PosTillMovement — append-only cash movement within a till session
-- ---------------------------------------------------------------------
create table pos_till_movements (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    till_session_id     bigint        not null references pos_till_sessions (id) on delete cascade,
    type                varchar(12)   not null,
    amount              bigint        not null,
    amount_currency     char(3)       not null,
    transaction_id       char(26),                             -- loose cross-module ref (pos.transactions)
    note                varchar(255),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_pos_till_movements_type
        check (type in ('PICKUP','DROP','SALE','CHANGE','REFUND_OUT'))
);

create index ix_pos_till_movements_till_session_id on pos_till_movements (till_session_id);

-- =====================================================================
-- Permissions for the POS "registers" slice (pos.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM12x ULIDs (exactly 26 chars) — collision-free vs the existing
-- seeded PERM01..PERM110 / LABELSZ01-05 / ROLE01 / USER01 set.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM120', 'pos.register.read',    'View registers',        'pos', 'List and view POS registers (terminals) and their bound peripherals'),
  ('01J0AA0000000000000PERM121', 'pos.register.write',   'Manage registers',      'pos', 'Create, update, delete registers, and bind/edit/test peripherals'),
  ('01J0AA0000000000000PERM122', 'pos.till.read',        'View till sessions',    'pos', 'List and view till sessions, their cash movements, and X/Z reports'),
  ('01J0AA0000000000000PERM123', 'pos.till.write',       'Manage till sessions',  'pos', 'Open a till, record cash pickups/drops, and close a till'),
  ('01J0AA0000000000000PERM124', 'pos.till.manage',      'Approve till variances','pos', 'Step-up manager authorization for an over-threshold till-close variance'),
  ('01J0AA0000000000000PERM127', 'pos.manager.operate',  'Operate manager-only registers', 'pos', 'Open a till session on a MANAGER_ONLY register');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'pos.register.read', 'pos.register.write',
    'pos.till.read', 'pos.till.write', 'pos.till.manage', 'pos.manager.operate')
where r.code = 'admin';
