-- =====================================================================
-- V51 — POS module, "transactions" sub-slice (the core sale).
--
-- Matches the JPA entities under
-- com.springboot.erp.modules.pos.transactions.domain extending BaseEntity:
--   ENT-PosTransaction      (header — the sale/receipt; OPEN -> PARKED/
--                            COMPLETED/VOIDED status workflow)
--   ENT-PosTransactionLine  (cart/receipt lines; price/tax/restriction
--                            snapshot at add time; weighed-goods support)
--   ENT-PosTender           (append-only payment legs; multi-tender)
--
-- Money is bigint minor units + char(3) currency (never float); qty is
-- numeric(12,3) to support weighed goods (fractional kg). Status/type
-- enums persist verbatim via @Enumerated(STRING) (the wire values already
-- match the Java constant names), so no AttributeConverter/lowercase-wire
-- mapping is needed here (unlike e.g. PoStatus).
--
-- Cross-slice references (register, till session, location, cashier,
-- customer, product, variant, tax code, payment method, the sale a refund
-- reverses) are held as loose ULID char(26) columns -- no hard cross-slice
-- FK, per the vertical-slice rule. Same-slice parent links (line/tender ->
-- header) are real FKs with cascade delete. All reference unique/check
-- constraints and indexes are reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-PosTransaction — US-031..035 / US-AU-003/004
-- ---------------------------------------------------------------------
create table pos_transactions (
    id                        bigint        generated by default as identity primary key,
    public_id                 char(26)      not null unique,

    register_id               char(26)      not null,               -- loose cross-slice ref
    till_session_id           char(26),                              -- loose cross-slice ref
    location_id               char(26)      not null,                -- loose cross-slice ref
    cashier_id                char(26),                              -- loose cross-slice ref (user)
    customer_id               char(26),                              -- loose cross-slice ref

    type                      varchar(8)    not null default 'SALE',
    status                    varchar(12)   not null default 'OPEN',
    refund_of_id              char(26),                              -- loose ref to the sale this refund reverses
    receipt_number            varchar(40),
    document_type             varchar(16),

    subtotal_amount           bigint        not null default 0,
    tax_amount                bigint        not null default 0,
    discount_amount           bigint        not null default 0,
    manual_discount_amount    bigint        not null default 0,
    manual_discount_reason    varchar(200),
    manager_approval_by       char(26),                              -- loose cross-slice ref (user)
    manager_approval_name     varchar(200),
    manager_approval_at       timestamptz,

    surcharge_amount          bigint        not null default 0,
    surcharge_tax_amount      bigint        not null default 0,
    surcharge_taxable         boolean       not null default false,
    surcharge_method_id       char(26),                              -- loose cross-slice ref
    surcharge_label           varchar(100),

    total_amount              bigint        not null default 0,
    paid_amount               bigint        not null default 0,
    change_amount             bigint        not null default 0,
    currency                  char(3)       not null default 'USD',

    age_verified              boolean       not null default false,
    age_verified_at           timestamptz,
    age_verified_by           char(26),                              -- loose cross-slice ref (user)
    age_id_type               varchar(40),

    reprint_count             integer       not null default 0,
    offline_origin            boolean       not null default false,
    client_txn_uuid           varchar(36)   unique,

    occurred_at               timestamptz   not null default now(),
    completed_at              timestamptz,

    created_at                timestamptz   not null default now(),
    created_by                char(26),
    updated_at                timestamptz   not null default now(),
    updated_by                char(26),
    deleted_at                timestamptz,
    version                   bigint        not null default 0,

    constraint ck_pos_txn_status check (status in ('OPEN','PARKED','COMPLETED','VOIDED')),
    constraint ck_pos_txn_type   check (type in ('SALE','REFUND'))
);

create index ix_pos_txn_register       on pos_transactions (register_id);
create index ix_pos_txn_location       on pos_transactions (location_id);
create index ix_pos_txn_till_session   on pos_transactions (till_session_id);
create index ix_pos_txn_status         on pos_transactions (status);
create index ix_pos_txn_receipt_number on pos_transactions (receipt_number);

-- ---------------------------------------------------------------------
-- ENT-PosTransactionLine
-- ---------------------------------------------------------------------
create table pos_transaction_lines (
    id                                bigint        generated by default as identity primary key,
    public_id                        char(26)      not null unique,

    transaction_id                    bigint        not null references pos_transactions (id) on delete cascade,
    line_no                           integer       not null,
    product_id                       char(26)      not null,        -- loose cross-slice ref
    variant_id                       char(26),                      -- loose cross-slice ref
    sku                               varchar(50)   not null,
    name                              varchar(200)  not null,
    barcode                           varchar(64),

    qty                               numeric(12,3) not null,
    free_qty                         numeric(12,3) not null default 0,
    unit_price_amount                 bigint        not null,
    base_price_amount                bigint        not null default 0,
    currency                          char(3)       not null,
    discount_amount                   bigint        not null default 0,
    promotion_label                  varchar(200),

    tax_code_id                      char(26),                      -- loose cross-slice ref
    tax_rate                         numeric(5,2)  not null default 0,
    tax_inclusive                     boolean       not null default false,
    tax_amount                       bigint        not null default 0,
    line_net_amount                   bigint        not null default 0,
    line_total_amount                 bigint        not null default 0,

    is_restricted_18                  boolean       not null default false,
    is_restricted_21                  boolean       not null default false,
    is_restricted_controlled_display  boolean       not null default false,

    refund_of_line_id                 char(26),                     -- loose ref (sale line a refund line reverses)
    refunded_qty                      numeric(12,3) not null default 0,
    void_reason                       varchar(120),

    reward_promotion_id               char(26),                     -- loose cross-slice ref
    weighed_qty_kg                     numeric(12,3),
    unit_cost_amount                   bigint,

    created_at                        timestamptz   not null default now(),
    created_by                        char(26),
    updated_at                         timestamptz   not null default now(),
    updated_by                         char(26),
    deleted_at                         timestamptz,
    version                            bigint        not null default 0,

    constraint uq_pos_line_no           unique (transaction_id, line_no),
    constraint ck_pos_line_qty_positive check (qty > 0)
);

create index ix_pos_lines_transaction on pos_transaction_lines (transaction_id);
create index ix_pos_lines_product     on pos_transaction_lines (product_id);

-- ---------------------------------------------------------------------
-- ENT-PosTender — US-033 FR-172..176 (append-only payment legs)
-- ---------------------------------------------------------------------
create table pos_tenders (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    transaction_id      bigint        not null references pos_transactions (id) on delete cascade,
    sequence            integer       not null,
    payment_method_id   char(26)      not null,        -- loose cross-slice ref
    method_type         varchar(20)   not null,
    amount_amount       bigint        not null,
    amount_currency     char(3)       not null,
    tendered_amount     bigint,
    change_amount       bigint        not null default 0,
    reference           varchar(120),
    masked_pan          varchar(8),
    is_reversed         boolean       not null default false,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at           timestamptz   not null default now(),
    updated_by           char(26),
    deleted_at           timestamptz,
    version              bigint        not null default 0,

    constraint uq_pos_tender_sequence unique (transaction_id, sequence)
);

create index ix_pos_tenders_transaction on pos_tenders (transaction_id);

-- =====================================================================
-- Permissions for the POS "transactions" slice (pos.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM126/PERM128 ULIDs (exactly 26 chars) — collision-free vs the
-- existing seeded PERM01..PERM110 and V50 pos/registers, which claims
-- PERM120..124 AND PERM127 (pos.manager.operate) — NOT a contiguous
-- PERM120..125 block — plus V52 pos/aux PERM132..138. PERM127 is therefore
-- skipped here; PERM125/129/130/131 remain free for future slices.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM126', 'pos.transaction.read',  'View POS transactions', 'pos', 'List, filter, and view POS sales/refunds, their lines, and tenders'),
  ('01J0AA0000000000000PERM128', 'pos.transaction.write', 'Operate POS sales',     'pos', 'Open a cart, add/edit/void lines, tender payment, complete/void, park/resume a sale');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'pos.transaction.read', 'pos.transaction.write')
where r.code = 'admin';
