-- =====================================================================
-- V52 — POS module, "aux" sub-slice (auxiliary checkout flows).
--
-- Matches the JPA entities under com.springboot.erp.modules.pos.aux.domain
-- extending BaseEntity:
--   PosParkedSale  (US-035 FR-182..186 — a parked cart keyed by a short,
--                   human-typeable code so a lane can be freed for the next
--                   customer and resumed later)
--   PosRefund      (US-034 FR-177..180 — refund metadata attached to a
--                   REFUND-type POS transaction, full or partial, receipt-
--                   linked or manager-gated no-receipt)
--   PosEvent       (FR-AU-013 / FR-198 / FR-25.8 — append-only POS-domain
--                   event/audit trail for compliance/review and
--                   receipt/journal purposes; distinct from the platform
--                   audit_logs hash-chained mutation trail)
--
-- All three are auxiliary to the (not-yet-ported) PosTransaction aggregate,
-- so every reference to a transaction/line/register/location/user is a
-- loose ULID char(26) column — no hard cross-slice FK, per the
-- vertical-slice rule. Money is bigint minor units + char(3) currency.
-- Enums persist verbatim via @Enumerated(STRING) (their wire values already
-- match the Java constant names) — no AttributeConverter needed.
-- =====================================================================

-- ---------------------------------------------------------------------
-- PosParkedSale — US-035 FR-182..186
-- ---------------------------------------------------------------------
create table pos_parked_sales (
    id              bigint      generated by default as identity primary key,
    public_id       char(26)    not null unique,

    transaction_id  char(26)    not null,          -- loose cross-slice ref (pos transaction)
    register_id     char(26)    not null,          -- loose cross-slice ref (register)
    location_id     char(26)    not null,          -- loose cross-slice ref (location)
    park_code       varchar(12) not null,
    parked_by       char(26),                      -- loose ref to users
    parked_at       timestamptz not null default now(),
    expires_at      timestamptz not null,
    resumed_at      timestamptz,
    note            varchar(255),

    created_at      timestamptz not null default now(),
    created_by      char(26),
    updated_at      timestamptz not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint      not null default 0
);

create index ix_pos_parked_sales_transaction_id on pos_parked_sales (transaction_id);
create index ix_pos_parked_sales_location_id on pos_parked_sales (location_id);

-- Reference uq_parked_active_code: a park_code may be reused once its park is
-- resumed, but must never collide with another still-active (unresumed) park.
create unique index uq_pos_parked_sales_active_code
    on pos_parked_sales (park_code)
    where resumed_at is null;

-- ---------------------------------------------------------------------
-- PosRefund — US-034 FR-177..180
-- ---------------------------------------------------------------------
create table pos_refunds (
    id                        bigint      generated by default as identity primary key,
    public_id                 char(26)    not null unique,

    transaction_id            char(26)    not null,   -- loose cross-slice ref (the REFUND txn)
    original_transaction_id   char(26),                -- loose cross-slice ref (the SALE refunded)
    mode                      varchar(16) not null,
    priced_from               varchar(16),
    manager_approval_by       char(26),                -- loose ref to users (VERIFIED manager)
    manager_approval_at       timestamptz,
    manager_approval_method   varchar(24),
    total_refund_amount       bigint      not null default 0,
    total_refund_currency     char(3)     not null,
    reason                    varchar(255),

    created_at                timestamptz not null default now(),
    created_by                char(26),
    updated_at                timestamptz not null default now(),
    updated_by                char(26),
    deleted_at                timestamptz,
    version                   bigint      not null default 0,

    constraint ck_pos_refunds_mode check (mode in ('RECEIPT_LINKED', 'NO_RECEIPT')),
    constraint ck_pos_refunds_priced_from
        check (priced_from is null or priced_from in ('ORIGINAL', 'LOWEST_30D', 'MANAGER_ENTERED')),
    constraint ck_pos_refunds_approval_method
        check (manager_approval_method is null
               or manager_approval_method in ('PASSWORD', 'OFFLINE_OPERATOR'))
);

create index ix_pos_refunds_transaction_id on pos_refunds (transaction_id);
create index ix_pos_refunds_original_transaction_id on pos_refunds (original_transaction_id);

-- ---------------------------------------------------------------------
-- PosEvent — FR-AU-013 / FR-198 / FR-25.8
-- ---------------------------------------------------------------------
create table pos_events (
    id              bigint      generated by default as identity primary key,
    public_id       char(26)    not null unique,

    transaction_id  char(26),                      -- loose cross-slice ref (pos transaction)
    register_id     char(26),                      -- loose cross-slice ref (register)
    type            varchar(40) not null,
    payload         jsonb       not null default '{}'::jsonb,
    needs_review    boolean     not null default false,
    reviewed_by     char(26),                      -- loose ref to users
    reviewed_at     timestamptz,

    created_at      timestamptz not null default now(),
    created_by      char(26),
    updated_at      timestamptz not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint      not null default 0,

    constraint ck_pos_events_type
        check (type in ('AGE_VERIFICATION_CONFIRMED', 'AGE_VERIFICATION_REFUSED',
                        'OFFLINE_SYNC_CONFLICT', 'OFFLINE_MAX_DURATION_BLOCKED',
                        'MANUAL_DISCOUNT_APPLIED', 'PERIPHERAL_FAILURE',
                        'MANAGER_OVERRIDE_GRANTED', 'MANAGER_OVERRIDE_DENIED'))
);

create index ix_pos_events_transaction_id on pos_events (transaction_id);
create index ix_pos_events_register_id on pos_events (register_id);
create index ix_pos_events_type on pos_events (type);
create index ix_pos_events_needs_review on pos_events (needs_review);

-- =====================================================================
-- Permissions for the POS "aux" slice (pos.<concept>.read/.write), granted
-- to the admin role so the @PreAuthorize checks are reachable. Fresh
-- PERM13x ULIDs (exactly 26 chars) — collision-free vs the existing seeded
-- PERM01..PERM110 / LABELSZ01-05 / ROLE01 / USER01 set. Includes
-- pos.refund.no_receipt (reference PERMISSION_POS_REFUND_NO_RECEIPT,
-- US-034 FR-178) — the elevated permission a VERIFIED step-up manager must
-- hold to approve a no-receipt refund (checked live by
-- RefundCommandService/ManagerStepUpAuthorizer, distinct from the plain
-- pos.refund.write a cashier holds to issue a receipt-linked refund).
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM132', 'pos.parked_sale.read',   'View parked sales',      'pos', 'List and view parked (suspended) POS carts'),
  ('01J0AA0000000000000PERM133', 'pos.parked_sale.write',  'Manage parked sales',    'pos', 'Park an open cart and resume a parked cart'),
  ('01J0AA0000000000000PERM134', 'pos.refund.read',        'View refunds',           'pos', 'List and view POS refunds and their manager-approval detail'),
  ('01J0AA0000000000000PERM135', 'pos.refund.write',       'Issue refunds',          'pos', 'Issue a receipt-linked or no-receipt POS refund'),
  ('01J0AA0000000000000PERM136', 'pos.event.read',         'View POS events',       'pos', 'List and view the POS operational event/audit timeline'),
  ('01J0AA0000000000000PERM137', 'pos.event.write',        'Record POS events',      'pos', 'Record and review POS-domain events (peripheral failures, age refusals, overrides)'),
  ('01J0AA0000000000000PERM138', 'pos.refund.no_receipt', 'Approve no-receipt refunds', 'pos', 'Manager step-up approval to issue a refund with no original receipt');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'pos.parked_sale.read', 'pos.parked_sale.write',
    'pos.refund.read', 'pos.refund.write', 'pos.refund.no_receipt',
    'pos.event.read', 'pos.event.write')
where r.code = 'admin';
