-- =====================================================================
-- V60 — CRM module, "customers" sub-slice (customer master).
--
-- Matches the JPA entities under com.guru.erp.modules.crm.customers.domain
-- extending BaseEntity:
--   ENT-050  Customer               (core record)
--   ENT-051  CustomerProfile        (1:1 CRM contact + per-channel consent)
--   ConsentLog                      (append-only consent-toggle audit trail)
--   ENT-073  CustomerSegment        (static or dynamic customer grouping)
--   ENT-073a CustomerSegmentMember  (segment membership rows)
--
-- company_id / preferred_location_id / linked_promotion_ids / recorded_by /
-- consent_email_by / consent_sms_by are loose cross-module ULID char(26)
-- references (settings.company, settings.location, products.promotion,
-- access.user) — no hard cross-module FK, per the vertical-slice rule.
-- CustomerProfile -> Customer, ConsentLog -> Customer, and
-- CustomerSegmentMember -> (CustomerSegment, Customer) ARE same-slice, so
-- they keep real FKs with cascade delete. All reference unique/check
-- constraints and indexes are reproduced.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-050 Customer — US-038 / FR-199-204
-- ---------------------------------------------------------------------
create table customers (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,               -- loose cross-module ref (settings.company)
    membership_id       varchar(20)   not null,
    first_name          varchar(100)  not null,
    last_name           varchar(100)  not null,
    type                varchar(16)   not null default 'INDIVIDUAL',
    status              varchar(16)   not null default 'ACTIVE',
    analytics_consent   boolean       not null default false,
    photo_url           text,
    anonymized          boolean       not null default false,
    anonymized_at       timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_customers_membership_id unique (membership_id),
    constraint ck_customers_type   check (type in ('INDIVIDUAL','BUSINESS')),
    constraint ck_customers_status check (status in ('ACTIVE','INACTIVE','ON_HOLD','ANONYMIZED'))
);

create index ix_customers_company_id on customers (company_id);

-- ---------------------------------------------------------------------
-- ENT-051 CustomerProfile — 1:1 CRM contact + consent extension
-- ---------------------------------------------------------------------
create table customer_profiles (
    id                      bigint        generated by default as identity primary key,
    public_id               char(26)      not null unique,

    customer_id             bigint        not null unique references customers (id) on delete cascade,
    mobile                  varchar(32),
    email                   varchar(255),
    postcode                varchar(16),
    date_of_birth           date,
    preferred_location_id   char(26),                          -- loose cross-module ref (settings.location)

    consent_email           boolean       not null default false,
    consent_sms              boolean       not null default false,
    consent_email_at          timestamptz,
    consent_sms_at            timestamptz,
    consent_email_by          char(26),                        -- loose cross-module ref (access.user)
    consent_sms_by            char(26),                        -- loose cross-module ref (access.user)

    created_at              timestamptz   not null default now(),
    created_by              char(26),
    updated_at               timestamptz   not null default now(),
    updated_by               char(26),
    deleted_at                timestamptz,
    version                   bigint        not null default 0
);

-- FR-200 — mobile and email are each unique per tenant when present.
create unique index uq_customer_profiles_mobile on customer_profiles (mobile) where mobile is not null;
create unique index uq_customer_profiles_email on customer_profiles (email) where email is not null;

-- ---------------------------------------------------------------------
-- ConsentLog — append-only consent-toggle history (FR-201 audit trail)
-- ---------------------------------------------------------------------
create table customer_consent_log (
    id              bigint        generated by default as identity primary key,
    public_id       char(26)      not null unique,

    customer_id     bigint        not null references customers (id) on delete cascade,
    channel         varchar(8)    not null,
    granted         boolean       not null,
    recorded_at     timestamptz   not null default now(),
    recorded_by     char(26),                                  -- loose cross-module ref (access.user)

    created_at      timestamptz   not null default now(),
    created_by      char(26),
    updated_at      timestamptz   not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint        not null default 0,

    constraint ck_consent_log_channel check (channel in ('EMAIL','SMS'))
);

create index ix_customer_consent_log_customer_id on customer_consent_log (customer_id);
create index ix_customer_consent_log_recorded_at on customer_consent_log (recorded_at);

-- ---------------------------------------------------------------------
-- ENT-073 CustomerSegment — static or dynamic grouping (US-042 / FR-219-222)
-- ---------------------------------------------------------------------
create table customer_segments (
    id                      bigint        generated by default as identity primary key,
    public_id               char(26)      not null unique,

    company_id              char(26)      not null,            -- loose cross-module ref (settings.company)
    code                    varchar(40)   not null,
    name                    varchar(120)  not null,
    description             text,
    mode                    varchar(8)    not null default 'STATIC',
    definition              jsonb         not null default '[]'::jsonb,
    rule_logic              varchar(3)    not null default 'AND',
    linked_promotion_ids    jsonb         not null default '[]'::jsonb,
    refreshed_at            timestamptz,

    created_at              timestamptz   not null default now(),
    created_by              char(26),
    updated_at              timestamptz   not null default now(),
    updated_by              char(26),
    deleted_at              timestamptz,
    version                 bigint        not null default 0,

    constraint uq_customer_segments_company_code unique (company_id, code),
    constraint ck_customer_segments_mode check (mode in ('STATIC','DYNAMIC'))
);

create index ix_customer_segments_company_id on customer_segments (company_id);

-- ---------------------------------------------------------------------
-- ENT-073a CustomerSegmentMember — membership rows
-- ---------------------------------------------------------------------
create table customer_segment_members (
    id              bigint        generated by default as identity primary key,
    public_id       char(26)      not null unique,

    segment_id      bigint        not null references customer_segments (id) on delete cascade,
    customer_id     bigint        not null references customers (id) on delete cascade,
    added_at        timestamptz   not null default now(),

    created_at      timestamptz   not null default now(),
    created_by      char(26),
    updated_at      timestamptz   not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint        not null default 0,

    constraint uq_customer_segment_members_unique unique (segment_id, customer_id)
);

create index ix_customer_segment_members_segment_id on customer_segment_members (segment_id);
create index ix_customer_segment_members_customer_id on customer_segment_members (customer_id);

-- =====================================================================
-- Permissions for the CRM "customers" slice (crm.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM14x ULIDs (exactly 26 chars) — collision-free vs the existing
-- seeded PERM01..PERM110 / PERM120..138 set. Assigned range PERM140..146;
-- PERM140..145 are used below, PERM146 is reserved (unused) for this
-- slice's future growth.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM140', 'crm.customer.read',         'View customers',            'crm', 'List, search, look up, and view customers and their profile/consent'),
  ('01J0AA0000000000000PERM141', 'crm.customer.write',        'Manage customers',          'crm', 'Create, update, anonymize, and delete customers'),
  ('01J0AA0000000000000PERM142', 'crm.customer.consent.write','Manage customer consent',   'crm', 'Capture a customer marketing/data consent toggle'),
  ('01J0AA0000000000000PERM143', 'crm.segment.read',          'View customer segments',    'crm', 'List and view customer segments and their membership'),
  ('01J0AA0000000000000PERM144', 'crm.segment.write',         'Manage customer segments',  'crm', 'Create, update, and delete customer segments'),
  ('01J0AA0000000000000PERM145', 'crm.segment.member.write',  'Manage segment membership', 'crm', 'Add or remove customers from a static customer segment');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'crm.customer.read', 'crm.customer.write', 'crm.customer.consent.write',
    'crm.segment.read', 'crm.segment.write', 'crm.segment.member.write')
where r.code = 'admin';
