-- =====================================================================
-- V61 — CRM module, "loyalty" sub-slice (US-039 loyalty program mechanics
-- + US-041 purchase-history projection feeding loyalty/segment logic).
--
-- Matches the JPA entities under com.springboot.erp.modules.crm.loyalty.domain
-- extending BaseEntity:
--   ENT-072  LoyaltyConfig        (one loyalty program per company)
--   ENT-070  LoyaltyAccount       (1:1 per-customer points balance)
--   ENT-071  LoyaltyLedger        (append-only point earn/redeem/expire/reverse)
--   CustomerTransaction           (purchase-history read projection, no PRD
--                                  entity number — reference has none either)
--
-- Cross-slice references (company, customer, location, acting user, the
-- customer-transaction / POS-sale a ledger row references) are held as loose
-- ULID char(26) columns — no hard cross-slice FK, per the vertical-slice
-- rule; this slice does not own Company or Customer. LoyaltyAccount.company_id
-- is denormalized at account-creation time (supplied by the caller) so the
-- config lookup never needs to hard-call the CRM customer sub-slice.
--
-- earn_rule / redeem_rule / tiers on LoyaltyConfig and payment_summary / lines
-- on CustomerTransaction are opaque jsonb columns (reference stores the same
-- shapes as JSON on the SQLAlchemy model). Money-bearing columns are bigint
-- minor units + char(3) currency (platform Money embeddable / convention),
-- never float/numeric.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-072 LoyaltyConfig — US-039 / FR-205-207 (one program per company)
-- ---------------------------------------------------------------------
create table loyalty_configs (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,               -- loose cross-slice ref (settings.company)
    name                varchar(120)  not null default 'Loyalty Program',
    active              boolean       not null default true,
    currency            char(3)       not null,

    earn_rule           jsonb         not null default '{"currencyUnitPerPoint":1,"eligibleCategoryIds":[]}'::jsonb,
    redeem_rule         jsonb         not null default '{"pointsPerCurrencyUnit":100,"minBalanceForRedemption":0}'::jsonb,
    expiry_months       integer       default 24,
    tiers               jsonb         not null default '[]'::jsonb,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_loyalty_configs_company unique (company_id)
);

-- ---------------------------------------------------------------------
-- ENT-070 LoyaltyAccount — FR-208 / FR-209 (1:1 with customer)
-- ---------------------------------------------------------------------
create table loyalty_accounts (
    id                          bigint        generated by default as identity primary key,
    public_id                   char(26)      not null unique,

    customer_id                 char(26)      not null,       -- loose cross-slice ref (CRM customer)
    company_id                  char(26)      not null,       -- loose cross-slice ref, denormalised at creation
    points_balance               bigint        not null default 0,
    tier_id                      char(26),                    -- references an id in loyalty_configs.tiers
    lifetime_spend_amount        bigint        not null default 0,
    rolling_12m_spend_amount      bigint        not null default 0,
    spend_currency                char(3)       not null,
    tier_recalculated_at          timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_loyalty_accounts_customer unique (customer_id),
    constraint ck_loyalty_accounts_balance_non_negative check (points_balance >= 0)
);

create index ix_loyalty_accounts_company_id on loyalty_accounts (company_id);

-- ---------------------------------------------------------------------
-- ENT-071 LoyaltyLedger — FR-209 (append-only point movements)
-- ---------------------------------------------------------------------
create table loyalty_ledger (
    id                       bigint        generated by default as identity primary key,
    public_id                char(26)      not null unique,

    customer_id              char(26)      not null,          -- loose cross-slice ref (CRM customer)
    type                     varchar(8)    not null,
    points_signed             bigint        not null,          -- signed: + on EARN, - on REDEEM/EXPIRE/REVERSE
    remaining                bigint        not null default 0, -- FIFO bookkeeping: unspent points on EARN rows
    occurred_at              timestamptz   not null default now(),
    expires_at               timestamptz,
    source_transaction_id     char(26),                        -- loose ref (CustomerTransaction / POS sale)
    description              varchar(255),
    actor_user_id             char(26),                        -- loose cross-slice ref (access.user)

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_loyalty_ledger_type check (type in ('EARN','REDEEM','EXPIRE','REVERSE'))
);

create index ix_loyalty_ledger_customer_id             on loyalty_ledger (customer_id);
create index ix_loyalty_ledger_occurred_at              on loyalty_ledger (occurred_at);
create index ix_loyalty_ledger_source_transaction_id     on loyalty_ledger (source_transaction_id);

-- ---------------------------------------------------------------------
-- CustomerTransaction — US-041 / FR-215-217 (purchase-history projection)
-- ---------------------------------------------------------------------
create table customer_transactions (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    customer_id         char(26)      not null,               -- loose cross-slice ref (CRM customer)
    receipt_number       varchar(40)   not null,
    type                 varchar(8)    not null default 'SALE',
    occurred_at          timestamptz   not null default now(),
    total_amount         bigint        not null default 0,
    subtotal_amount       bigint,                              -- goods-only, tax-exclusive; null on legacy rows
    total_currency        char(3)       not null,
    location_id          char(26),                             -- loose cross-slice ref (settings.location)
    payment_summary       jsonb         not null default '[]'::jsonb,  -- masked at write time (FR-217)
    lines                jsonb         not null default '[]'::jsonb,
    refund_of_id          char(26),                             -- loose ref to the sale a REFUND row reverses

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint ck_customer_transactions_type check (type in ('SALE','REFUND')),
    -- Idempotency key for the outbox-fed projection writer: at-least-once
    -- redelivery of the same POS event must not duplicate the projection
    -- (reference _existing_projection / record_pos_transaction).
    constraint uq_customer_transactions_receipt unique (customer_id, receipt_number, type)
);

create index ix_customer_transactions_customer_occurred on customer_transactions (customer_id, occurred_at);

-- =====================================================================
-- Permissions for the CRM "loyalty" slice (crm.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM147..PERM152 ULIDs (exactly 26 chars) — this slice's strictly
-- assigned range; no number outside PERM147..PERM152 is used here.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM147', 'crm.loyaltyconfig.read',       'View loyalty program',        'crm', 'View the company loyalty program config, earn/redeem rules, and tiers'),
  ('01J0AA0000000000000PERM148', 'crm.loyaltyconfig.write',      'Manage loyalty program',      'crm', 'Create/update the company loyalty program config and manage tiers'),
  ('01J0AA0000000000000PERM149', 'crm.loyaltyaccount.read',      'View loyalty accounts',       'crm', 'View a customer''s loyalty points balance and ledger history'),
  ('01J0AA0000000000000PERM150', 'crm.loyaltyaccount.write',     'Operate loyalty points',      'crm', 'Earn, redeem, reverse, and expire a customer''s loyalty points'),
  ('01J0AA0000000000000PERM151', 'crm.customertransaction.read', 'View purchase history',       'crm', 'View a customer''s projected purchase (POS/Sales) history'),
  ('01J0AA0000000000000PERM152', 'crm.customertransaction.write','Record purchase history',     'crm', 'Ingest a POS/Sales transaction into a customer''s purchase-history projection');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'crm.loyaltyconfig.read', 'crm.loyaltyconfig.write',
    'crm.loyaltyaccount.read', 'crm.loyaltyaccount.write',
    'crm.customertransaction.read', 'crm.customertransaction.write')
where r.code = 'admin';
