-- =====================================================================
-- V70 — FINANCE module, "coa" sub-slice (Chart of Accounts).
--
-- Matches the JPA entities under com.springboot.erp.modules.finance.coa.domain
-- extending BaseEntity:
--   ENT-016  Account         (nested-set chart-of-accounts tree)
--   ENT-018  AccountMapping  (module + purpose -> GL account)
--
-- Reference: guru-erp-revamp/backend/app/finance/models.py (Account,
-- AccountMapping), nested_set.py (lft/rgt/depth invariants), constants.py
-- (AccountType / AccountPostingType / AccountStatus / AccountModule /
-- AccountPurpose enums), views/chart_of_accounts.py, views/coa_management.py.
--
-- company_id / opening_location_id are loose cross-module ULID char(26)
-- references (settings.company, settings.location) — no hard cross-module
-- FK, per the vertical-slice rule. accounts.parent_id IS a same-slice
-- self-referencing FK (nested-set tree) and account_mappings.account_id IS
-- a same-slice FK to accounts — both keep real FKs.
--
-- GL is financial data — every check constraint from the reference is
-- reproduced EXACTLY below (ck_accounts_type / ck_accounts_posting_type /
-- ck_accounts_status / ck_account_mappings_module / ck_account_mappings_purpose),
-- plus the uq_accounts_company_code and uq_account_mappings_company_module_purpose
-- uniqueness rules.
--
-- NOTE on soft-delete + nested-set interaction: Account extends BaseEntity
-- (consistency over a hypothetical edge case, per the task brief) so its
-- @SQLRestriction("deleted_at is null") applies like every other entity.
-- The NestedSetService's raw SQL UPDATE shifts explicitly filter
-- "deleted_at is null" themselves (mirroring the reference's own
-- Account.deleted_at.is_(None) predicates in nested_set.py) so a soft-deleted
-- row never participates in a lft/rgt shift, and JPA's own restriction keeps
-- it out of ordinary repository reads. Deletes in this slice are HARD
-- deletes (matching the reference db.delete(a) — a leaf with no postings),
-- which is what actually triggers close_delete_gap; soft-delete via
-- BaseEntity.softDelete() is not used for Account today, but the column and
-- restriction stay for platform consistency and for AccountMapping.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-016 Account — US-043 / FR-223-227 — nested-set chart of accounts
-- ---------------------------------------------------------------------
create table accounts (
    id                      bigint        generated by default as identity primary key,
    public_id               char(26)      not null unique,

    company_id              char(26)      not null,             -- loose cross-module ref (settings.company)
    code                    varchar(20)   not null,
    name                    varchar(200)  not null,
    type                    varchar(16)   not null,
    parent_id               bigint        references accounts (id) on delete restrict,
    posting_type            varchar(16)   not null default 'POSTING',
    currency                char(3),
    status                  varchar(16)   not null default 'active',

    -- Opening-balance fields — populated when an admin seeds an account with
    -- a prior-period balance via the COA drawer. Stored on the account so
    -- the UI can surface what was seeded without re-querying the journal.
    opening_debit_amount    bigint        not null default 0,
    opening_credit_amount   bigint        not null default 0,
    opening_date            timestamptz,
    opening_location_id     char(26),                            -- loose cross-module ref (settings.location)

    -- Nested-set columns (Joe Celko modified preorder traversal) for O(1)
    -- ancestor/descendant queries. Reassigned only by the incremental
    -- insert/delete/move shifts in NestedSetService — never a full rebuild
    -- on single-row CRUD.
    lft                     integer       not null default 0,
    rgt                     integer       not null default 0,
    depth                   integer       not null default 0,

    created_at              timestamptz   not null default now(),
    created_by              char(26),
    updated_at              timestamptz   not null default now(),
    updated_by              char(26),
    deleted_at              timestamptz,
    version                 bigint        not null default 0,

    constraint uq_accounts_company_code unique (company_id, code),
    constraint ck_accounts_type check (type in ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
    constraint ck_accounts_posting_type check (posting_type in ('POSTING','HEADER')),
    constraint ck_accounts_status check (status in ('active','inactive'))
);

create index ix_accounts_company_id on accounts (company_id);
create index ix_accounts_parent_id on accounts (parent_id);
-- Nested-set range queries (ancestor/descendant containment, subtree fetch)
-- and the lft-order pre-order-DFS listing both hinge on this index.
create index ix_accounts_company_lft on accounts (company_id, lft);

-- ---------------------------------------------------------------------
-- ENT-018 AccountMapping — maps (company, module, purpose) -> GL account.
-- One row per company per (module, purpose) pair.
-- ---------------------------------------------------------------------
create table account_mappings (
    id              bigint        generated by default as identity primary key,
    public_id       char(26)      not null unique,

    company_id      char(26)      not null,                      -- loose cross-module ref (settings.company)
    module          varchar(30)   not null,
    purpose         varchar(50)   not null,
    account_id      bigint        not null references accounts (id) on delete restrict,

    created_at      timestamptz   not null default now(),
    created_by      char(26),
    updated_at      timestamptz   not null default now(),
    updated_by      char(26),
    deleted_at      timestamptz,
    version         bigint        not null default 0,

    constraint uq_account_mappings_company_module_purpose unique (company_id, module, purpose),
    constraint ck_account_mappings_module check (module in ('INVENTORY','PROCUREMENT','SALES','FINANCE','POS')),
    constraint ck_account_mappings_purpose check (purpose in (
        'ACCOUNTS_RECEIVABLE','ACCOUNTS_PAYABLE','GST_PAYABLE','EXCHANGE_GAIN_LOSS',
        'INVENTORY_ASSET','INVENTORY_VARIANCE','COST_OF_GOODS_SOLD',
        'GRN_CLEARING','PURCHASE_ACCOUNT','PURCHASE_DISCOUNT','PURCHASE_RETURN','FREIGHT_LANDED_COST',
        'PURCHASE_PRICE_VARIANCE','INVOICE_PENDING_RECEIPT','BANK_ACCOUNT',
        'SALES_REVENUE','SALES_DISCOUNT','SALES_RETURN','DELIVERY_INCOME',
        'CASH_ON_HAND','CARD_CLEARING','CASH_OVER_SHORT','SURCHARGE_REVENUE',
        'OPENING_BALANCE_EQUITY'
    ))
);

create index ix_account_mappings_company_id on account_mappings (company_id);
create index ix_account_mappings_account_id on account_mappings (account_id);

-- =====================================================================
-- Permissions for the FINANCE "coa" slice (finance.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM16x ULIDs (exactly 26 chars) — collision-free vs the existing
-- seeded PERM01..PERM110 / PERM120..146 / PERM14x set (grep-verified against
-- every V*.sql before finalizing). Assigned range PERM160..165; all six are
-- used below (no unused reservation needed for this slice).
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM160', 'finance.coa.read',            'View chart of accounts',  'finance', 'List, search, and view GL accounts and the account tree'),
  ('01J0AA0000000000000PERM161', 'finance.coa.write',            'Manage chart of accounts','finance', 'Create, update, move, and delete GL accounts'),
  ('01J0AA0000000000000PERM162', 'finance.coa.import',           'Import chart of accounts','finance', 'Bulk CSV import of GL accounts'),
  ('01J0AA0000000000000PERM163', 'finance.account_mapping.read', 'View account mappings',   'finance', 'List account mappings and per-module mapping readiness'),
  ('01J0AA0000000000000PERM164', 'finance.account_mapping.write','Manage account mappings', 'finance', 'Create, update, and delete module/purpose GL account mappings'),
  ('01J0AA0000000000000PERM165', 'finance.coa.reserved',         'Reserved (finance coa)',  'finance', 'Reserved permission slot for future finance/coa growth');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'finance.coa.read', 'finance.coa.write', 'finance.coa.import',
    'finance.account_mapping.read', 'finance.account_mapping.write', 'finance.coa.reserved')
where r.code = 'admin';
