-- =====================================================================
-- V71 — FINANCE module, "gl" sub-slice (General Ledger core).
--
-- Matches the JPA entities under com.springboot.erp.modules.finance.gl.domain
-- extending BaseEntity:
--   ENT-046  JournalEntry    (header: company/location, voucher_type/number,
--                             entry_date, period_code, status, total_debit/credit,
--                             posted_at/by, reversed_by_id)
--   ENT-046a JournalLine     (line: account_id, holder_type/holder_id polymorphic
--                             ref, debit/credit + currency/exchange_rate/
--                             base_debit/base_credit)
--   ENT-046b VoucherType     (lookup: prefix/numbering per voucher kind)
--   GlPostingLog             (idempotency + reconciliation ledger for automated
--                             GL postings, e.g. POS -> GL)
--
-- company_id / location_id / account_id / holder_id / reversed_by_id /
-- journal_entry_id (on gl_posting_log) are loose cross-module ULID char(26)
-- references (settings.company, settings.location, a not-yet-ported
-- chart-of-accounts slice, supplier/customer/employee subledgers, and
-- journal_entries itself respectively) — no hard cross-module FK, per the
-- vertical-slice rule. journal_lines -> journal_entries IS same-slice
-- (aggregate parent/child), so it keeps a real FK with cascade delete.
--
-- The reference's debit-xor-credit invariant
-- ("(debit=0 AND credit>0) OR (debit>0 AND credit=0)") is reproduced EXACTLY
-- as ck_journal_lines_xor below — this is the single most important
-- constraint in this migration; it is also re-checked in BalancingService
-- before every persist so a violation surfaces as a clean DomainException
-- rather than an opaque DB error.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-046b VoucherType — US-044 / FR-228 voucher-type catalogue
-- ---------------------------------------------------------------------
create table voucher_types (
    id                      bigint        generated by default as identity primary key,
    public_id               char(26)      not null unique,

    code                    varchar(10)   not null,
    prefix                  varchar(8)    not null default 'JV',
    name                    varchar(80)   not null,
    description             varchar(500)  not null default '',
    operational             boolean       not null default false,
    operational_module      varchar(40),
    is_active               boolean       not null default true,

    created_at              timestamptz   not null default now(),
    created_by              char(26),
    updated_at              timestamptz   not null default now(),
    updated_by              char(26),
    deleted_at              timestamptz,
    version                 bigint        not null default 0,

    constraint uq_voucher_types_code unique (code),
    constraint ck_voucher_types_operational_xor_module check (
        (operational = false and operational_module is null) or
        (operational = true and operational_module is not null)
    )
);

-- ---------------------------------------------------------------------
-- ENT-046 JournalEntry — US-044 / FR-228 / FR-243 journal entry header
-- ---------------------------------------------------------------------
create table journal_entries (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,               -- loose cross-module ref (settings.company)
    location_id         char(26),                              -- loose cross-module ref (settings.location)
    voucher_type        varchar(10)   not null,
    voucher_number      varchar(40)   not null,
    entry_date          date          not null,
    period_code         varchar(10)   not null,                -- YYYY-MM, derived from entry_date
    reference           varchar(200),
    narration           varchar(1000) not null default '',
    status              varchar(16)   not null default 'DRAFT',
    -- Reversal link — the reversal entry that voided this one, if any. Loose
    -- same-table self-reference by public id (never both this AND a hard FK
    -- to preserve "immutable once posted/reversed" without a self-referencing
    -- FK ordering headache on insert).
    reversed_by_id      char(26),
    total_debit         bigint        not null default 0,
    total_credit        bigint        not null default 0,

    posted_at           timestamptz,
    posted_by           char(26),                              -- loose cross-module ref (access.user)

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_journal_entries_company_voucher unique (company_id, voucher_number),
    constraint ck_journal_entries_status check (status in ('DRAFT','POSTED','REVERSED'))
);

create index ix_journal_entries_company_id on journal_entries (company_id);
create index ix_journal_entries_voucher_type on journal_entries (voucher_type);
create index ix_journal_entries_entry_date on journal_entries (entry_date);
create index ix_journal_entries_period_code on journal_entries (period_code);
create index ix_journal_entries_status on journal_entries (status);

-- ---------------------------------------------------------------------
-- ENT-046a JournalLine — either debit OR credit > 0, never both, never
-- neither. THE hard invariant of this entire migration.
-- ---------------------------------------------------------------------
create table journal_lines (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    entry_id            bigint        not null references journal_entries (id) on delete cascade,
    line_no             integer       not null,
    account_id          char(26)      not null,                -- loose cross-module ref (chart-of-accounts, not yet ported)
    holder_type         varchar(16)   not null default 'NONE',
    holder_id           char(26),                               -- loose cross-module ref (supplier/customer/employee)
    narration           varchar(500)  not null default '',
    debit               bigint        not null default 0,
    credit              bigint        not null default 0,
    currency            char(3)       not null default 'USD',
    exchange_rate       numeric(18,8) not null default 1.0,
    base_debit          bigint        not null default 0,
    base_credit         bigint        not null default 0,
    -- Per-line branch override (transfer vouchers carry DR branch != CR branch).
    location_id         char(26),                               -- loose cross-module ref (settings.location)

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_journal_lines_entry_line unique (entry_id, line_no),
    constraint ck_journal_lines_nonneg check (debit >= 0 and credit >= 0),
    -- THE hard invariant: exactly one of debit/credit is strictly positive.
    constraint ck_journal_lines_xor check (
        (debit = 0 and credit > 0) or (debit > 0 and credit = 0)
    ),
    constraint ck_journal_lines_holder_type check (
        holder_type in ('NONE','SUPPLIER','CUSTOMER','EMPLOYEE')
    )
);

create index ix_journal_lines_entry_id on journal_lines (entry_id);
create index ix_journal_lines_account_id on journal_lines (account_id);
create index ix_journal_lines_holder on journal_lines (holder_type, holder_id);

-- ---------------------------------------------------------------------
-- GlPostingLog — idempotency + reconciliation ledger for automated GL
-- postings (e.g. POS -> GL via the pos.sale.completed outbox consumer).
-- The unique (source_kind, source_ref) index below IS the idempotency
-- key GlPostingConsumerService checks before applying any journal effect.
-- ---------------------------------------------------------------------
create table gl_posting_log (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,                -- loose cross-module ref (settings.company)
    source_kind         varchar(24)   not null,                -- e.g. 'POS_SALE' | 'POS_REFUND' | 'POS_VOID' | 'POS_TILL_DEPOSIT'
    source_ref          varchar(26)   not null,                -- public id of the source aggregate (e.g. pos_transaction)
    event_type          varchar(120)  not null,                -- outbox event_type that drove this attempt
    journal_entry_id    char(26),                              -- loose ref to the JournalEntry this attempt produced
    status              varchar(16)   not null,                -- 'POSTED' | 'SKIPPED' | 'FAILED'
    attempts            integer       not null default 0,
    last_error          text,
    request_id          varchar(64),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_gl_posting_log_source unique (source_kind, source_ref),
    constraint ck_gl_posting_log_status check (status in ('POSTED','SKIPPED','FAILED'))
);

create index ix_gl_posting_log_company_id on gl_posting_log (company_id);
create index ix_gl_posting_log_source_ref on gl_posting_log (source_ref);
create index ix_gl_posting_log_request_id on gl_posting_log (request_id);

-- =====================================================================
-- Permissions for the FINANCE "gl" slice (finance.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM166..174 ULIDs (exactly 26 chars, matching the V60 pattern),
-- collision-free vs every existing seeded PERM01..PERM152 range. Assigned
-- range PERM166..174 (9 codes); all 9 are used below.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM166', 'finance.journal.read',        'View journal entries',        'finance', 'List, search, and view journal entries and their lines'),
  ('01J0AA0000000000000PERM167', 'finance.journal.write',       'Manage journal entries',      'finance', 'Create, update, and delete DRAFT journal entries'),
  ('01J0AA0000000000000PERM168', 'finance.journal.post',        'Post and reverse journals',    'finance', 'Post a DRAFT journal entry to POSTED, and reverse a POSTED entry'),
  ('01J0AA0000000000000PERM169', 'finance.voucher_type.read',   'View voucher types',          'finance', 'List and view the voucher-type catalogue'),
  ('01J0AA0000000000000PERM170', 'finance.voucher_type.write',  'Manage voucher types',        'finance', 'Create, update, and delete non-operational voucher types'),
  ('01J0AA0000000000000PERM171', 'finance.gl_posting_log.read', 'View GL posting log',         'finance', 'View the idempotency/reconciliation feed for automated GL postings'),
  ('01J0AA0000000000000PERM172', 'finance.gl.read',             'View GL core (reserved)',     'finance', 'Reserved read permission for GL-core cross-cutting concerns'),
  ('01J0AA0000000000000PERM173', 'finance.gl.write',            'Manage GL core (reserved)',   'finance', 'Reserved write permission for GL-core cross-cutting concerns'),
  ('01J0AA0000000000000PERM174', 'finance.gl.admin',            'Administer GL core (reserved)','finance', 'Reserved administrative permission for GL-core cross-cutting concerns');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'finance.journal.read', 'finance.journal.write', 'finance.journal.post',
    'finance.voucher_type.read', 'finance.voucher_type.write',
    'finance.gl_posting_log.read', 'finance.gl.read', 'finance.gl.write', 'finance.gl.admin')
where r.code = 'admin';
