-- =====================================================================
-- V72 — FINANCE module, "periods" sub-slice (fiscal period close + BAS).
--
-- Matches the JPA entities under com.guru.erp.modules.finance.periods.domain
-- extending BaseEntity:
--   ENT-015      FiscalPeriod          (the fiscal period being closed —
--                                        DRAFT->OPEN->...->CLOSED->ARCHIVED)
--   PeriodChecklistItem                 (FR-249 ordered close checklist,
--                                        pending->passed/failed + sign-off)
--   PeriodApprovalStep                  (E-009 Phase 4 multi-step close
--                                        sign-off chain, PENDING->APPROVED/REJECTED)
--   PeriodSnapshot                      (E-009 Phase 5 frozen trial-balance
--                                        snapshot taken at close — read-only)
--   ENT-AU-001   BasPeriod              (BAS lodgement period, OPEN->LODGED->FROZEN)
--   ENT-AU-002   BasReport              (immutable BAS box-computation snapshot)
--
-- Reference: guru-erp-revamp/backend/app/finance/models_bas.py,
-- models_period_close.py, views/period_close.py, views/bas.py,
-- views/fiscal_periods.py (FiscalPeriod itself is defined in
-- app.business_settings.models but is owned by THIS slice in the port,
-- since every period-close/BAS concept keys off it and it was not ported
-- elsewhere).
--
-- company_id / owner_user_id / signed_off_by / approver_user_id /
-- generated_by / lodged_by / gst_account_id / revenue_account_id are loose
-- cross-module ULID char(26) references (settings.company, access.user, a
-- not-yet-ported chart-of-accounts slice) — no hard cross-module FK, per the
-- vertical-slice rule. period_checklist_items/period_approval_steps/
-- period_snapshots -> fiscal_periods AND bas_reports -> bas_periods ARE
-- same-slice (aggregate parent/child), so they keep real FKs with RESTRICT
-- delete (a period's history is never silently orphaned by deleting the
-- period row — these financial records are never hard-deleted in practice).
--
-- GL is financial data — every check constraint from the reference is
-- reproduced EXACTLY below (ck_fiscal_periods_status, ck_period_checklist_*,
-- ck_period_approval_status, ck_bas_periods_*), plus every uniqueness rule
-- (uq_fiscal_periods_company_period, uq_period_checklist_period_item,
-- uq_period_approval_period_sequence, uq_period_snapshots_period_version,
-- uq_bas_periods_company_period, uq_bas_reports_period_version).
-- =====================================================================

-- ---------------------------------------------------------------------
-- ENT-015 FiscalPeriod — US-? / FR-225 / FR-250 period-end lifecycle
-- ---------------------------------------------------------------------
create table fiscal_periods (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,                  -- loose cross-module ref (settings.company)
    period_code         varchar(7)    not null,
    date_from           date          not null,
    date_to             date          not null,
    status              varchar(16)   not null default 'OPEN',

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_fiscal_periods_company_period unique (company_id, period_code),
    constraint ck_fiscal_periods_status check (status in (
        'DRAFT','OPEN','PREPARING','RECONCILING','VALIDATING','PENDING_APPROVAL',
        'APPROVED','CLOSING','CLOSED','ADJUSTMENT','ARCHIVED'
    )),
    constraint ck_fiscal_periods_date_range check (date_to >= date_from)
);

create index ix_fiscal_periods_company_id on fiscal_periods (company_id);
create index ix_fiscal_periods_status on fiscal_periods (status);

-- ---------------------------------------------------------------------
-- PeriodChecklistItem — FR-249 period-close checklist (one row per
-- fiscal period per evaluator key).
-- ---------------------------------------------------------------------
create table period_checklist_items (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    fiscal_period_id    bigint        not null references fiscal_periods (id) on delete restrict,
    item_key            varchar(40)   not null,
    required            boolean       not null default true,
    owner_user_id       char(26),                                -- loose cross-module ref (access.user)

    check_status        varchar(16)   not null default 'PENDING',
    check_detail         jsonb,
    checked_at           timestamptz,

    signed_off_by        char(26),                               -- loose cross-module ref (access.user)
    signed_off_at         timestamptz,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_period_checklist_period_item unique (fiscal_period_id, item_key),
    constraint ck_period_checklist_check_status check (check_status in ('PENDING','PASSED','FAILED'))
);

create index ix_period_checklist_items_fiscal_period_id on period_checklist_items (fiscal_period_id);

-- ---------------------------------------------------------------------
-- PeriodApprovalStep — E-009 Phase 4 period-close approval chain.
-- ---------------------------------------------------------------------
create table period_approval_steps (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    fiscal_period_id    bigint        not null references fiscal_periods (id) on delete restrict,
    sequence_no         integer       not null,
    label               varchar(80)   not null,
    status              varchar(16)   not null default 'PENDING',
    approver_user_id    char(26),                                -- loose cross-module ref (access.user)
    decided_at           timestamptz,
    comment              varchar(500),

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_period_approval_period_sequence unique (fiscal_period_id, sequence_no),
    constraint ck_period_approval_status check (status in ('PENDING','APPROVED','REJECTED'))
);

create index ix_period_approval_steps_fiscal_period_id on period_approval_steps (fiscal_period_id);

-- ---------------------------------------------------------------------
-- PeriodSnapshot — E-009 Phase 5 immutable financial snapshot frozen at
-- period close (CLOSING -> CLOSED). Read-only historical record; a row
-- is NEVER updated after insert, only new versions are appended.
-- ---------------------------------------------------------------------
create table period_snapshots (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    fiscal_period_id    bigint        not null references fiscal_periods (id) on delete restrict,
    generated_at        timestamptz   not null default now(),
    generated_by        char(26),                                -- loose cross-module ref (access.user)
    payload             jsonb         not null,
    version_no          integer       not null default 1,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_period_snapshots_period_version unique (fiscal_period_id, version_no)
);

create index ix_period_snapshots_fiscal_period_id on period_snapshots (fiscal_period_id);

-- ---------------------------------------------------------------------
-- ENT-AU-001 BasPeriod — US-AU-005 BAS lodgement-period lifecycle
-- (OPEN -> LODGED -> FROZEN).
-- ---------------------------------------------------------------------
create table bas_periods (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    company_id          char(26)      not null,                  -- loose cross-module ref (settings.company)
    period_code         varchar(20)   not null,                  -- e.g. "2026-Q1", "2026-07", "2026"
    period_type         varchar(16)   not null,
    date_from           date          not null,
    date_to             date          not null,
    status              varchar(16)   not null default 'OPEN',
    lodged_at           timestamptz,
    lodged_by           char(26),                                -- loose cross-module ref (access.user)
    lodgement_reference varchar(120),

    -- Explicit GL account pointers this slice uses to compute BAS boxes,
    -- resolved at BasPeriod-creation time rather than via the (not-yet-ported)
    -- AccountMapping lookup the reference uses — keeps this slice decoupled
    -- from the coa sub-slice's mapping table (see BasReportGenerationService).
    gst_account_id       char(26),                                -- loose cross-module ref (finance.coa.Account)
    revenue_account_id   char(26),                                -- loose cross-module ref (finance.coa.Account)

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_bas_periods_company_period unique (company_id, period_code),
    constraint ck_bas_periods_status check (status in ('OPEN','LODGED','FROZEN')),
    constraint ck_bas_periods_period_type check (period_type in ('MONTHLY','QUARTERLY','ANNUAL')),
    constraint ck_bas_periods_date_range check (date_to >= date_from)
);

create index ix_bas_periods_company_id on bas_periods (company_id);

-- ---------------------------------------------------------------------
-- ENT-AU-002 BasReport — immutable snapshot of one BAS box-computation
-- run for a BasPeriod (FR-AU-020/021). Versioned; never updated after
-- insert, only appended.
-- ---------------------------------------------------------------------
create table bas_reports (
    id                  bigint        generated by default as identity primary key,
    public_id           char(26)      not null unique,

    bas_period_id       bigint        not null references bas_periods (id) on delete restrict,
    generated_at        timestamptz   not null default now(),
    generated_by        char(26),                                -- loose cross-module ref (access.user)
    box_values          jsonb         not null,                  -- {"G1":.., "1A":.., "netGst":..} minor units
    version_no          integer       not null default 1,

    created_at          timestamptz   not null default now(),
    created_by          char(26),
    updated_at          timestamptz   not null default now(),
    updated_by          char(26),
    deleted_at          timestamptz,
    version             bigint        not null default 0,

    constraint uq_bas_reports_period_version unique (bas_period_id, version_no)
);

create index ix_bas_reports_bas_period_id on bas_reports (bas_period_id);

-- =====================================================================
-- Permissions for the FINANCE "periods" slice (finance.<concept>.read/.write),
-- granted to the admin role so the @PreAuthorize checks are reachable.
-- Fresh PERM175..181 ULIDs (exactly 26 chars, matching the V60/V70/V71
-- pattern), collision-free vs every existing seeded PERM01..PERM174 range
-- (grep-verified against every V*.sql before finalizing). Assigned range
-- PERM175..181 (7 codes); all 7 are used below.
-- =====================================================================
insert into permissions (public_id, code, name, module, description) values
  ('01J0AA0000000000000PERM175', 'finance.period.read',   'View fiscal periods',        'finance', 'List, search, and view fiscal periods, their checklist, approvals, and snapshots'),
  ('01J0AA0000000000000PERM176', 'finance.period.write',  'Manage fiscal periods',      'finance', 'Create fiscal periods, transition their status, run checklist checks, set item owners, and sign off checklist items'),
  ('01J0AA0000000000000PERM177', 'finance.period.close',  'Approve period close',       'finance', 'Approve or reject a step in the period-close approval chain'),
  ('01J0AA0000000000000PERM178', 'finance.period.adjust', 'Adjust closed periods',      'finance', 'Post into an ADJUSTMENT-status period and reopen a CLOSED period back to OPEN'),
  ('01J0AA0000000000000PERM179', 'finance.bas.read',      'View BAS periods',           'finance', 'List and view BAS lodgement periods and their generated report history'),
  ('01J0AA0000000000000PERM180', 'finance.bas.write',     'Manage BAS periods',         'finance', 'Create BAS periods and transition their lodgement status (OPEN/LODGED/FROZEN)'),
  ('01J0AA0000000000000PERM181', 'finance.bas.generate',  'Generate BAS reports',       'finance', 'Run the BAS box computation and persist a new versioned report snapshot');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r
join permissions p on p.code in (
    'finance.period.read', 'finance.period.write', 'finance.period.close', 'finance.period.adjust',
    'finance.bas.read', 'finance.bas.write', 'finance.bas.generate')
where r.code = 'admin';
