package com.guru.erp.modules.inventory.stock.domain;

/**
 * Whether a {@link ProductBatch}'s barcode came from the manufacturer or was
 * generated by us (reference {@code product_batches.barcode_source} check).
 * Persisted lower-case to satisfy the check constraint, via
 * {@link BatchBarcodeSourceConverter}.
 */
public enum BatchBarcodeSource {
    MANUFACTURER("manufacturer"),
    GENERATED("generated");

    private final String wire;

    BatchBarcodeSource(String wire) {
        this.wire = wire;
    }

    public String wire() {
        return wire;
    }

    public static BatchBarcodeSource fromWire(String wire) {
        for (BatchBarcodeSource s : values()) {
            if (s.wire.equals(wire)) {
                return s;
            }
        }
        throw new IllegalArgumentException("Unknown barcode source: " + wire);
    }
}
